-- =============================================================================
-- OSG DOST TASK FORCE — DELETE + MERGE ALL 43 CASES + VERBATIM REMARKS
-- Source: OSG_DOST_Cases_1_to_43_VERBATIM_Status_Remarks (2).docx
-- Generated by supabase/generate_verbatim_sql.py
--
-- One file, one run:
--   1) DELETE old/extra cases
--   2) MERGE (upsert) official cases 1–43 by code
--   3) REPLACE all verbatim Status/Remarks
-- Paste into Supabase → SQL Editor → Run
-- =============================================================================

BEGIN;

ALTER TABLE public.cases ADD COLUMN IF NOT EXISTS report_case_number integer;

-- =============================================================================
-- PHASE 1: DELETE previous / extra cases
-- =============================================================================

-- Remove child rows for cases that are NOT in the official 43 codes
DELETE FROM public.case_status_updates
WHERE case_id IN (SELECT id FROM public.cases WHERE code NOT IN (
  'c-usigan-001', 'c-baculi-001', 'c-lasam-lakas-001', 'c-collado-001', 'c-yapit-001', 'c-carabacan-001', 'c-magana-001', 'c-mangaoang-001', 'c-chavez-001', 'c-ranjo-001', 'c-coloma-001', 'c-rosendo-001', 'c-mamauag-001', 'c-colobong-001', 'c-pagunuran-001', 'c-massalang-001', 'c-cruz-001', 'c-tumbali-001', 'c-abalos-001', 'c-cubacub-001', 'c-villanueva-001', 'c-galapon-001', 'c-tomas-001', 'c-domingo-001', 'c-uy-001', 'c-duerme-001', 'c-khong-001', 'c-garcia-001', 'c-dimaculangan-001', 'c-mallare-001', 'c-lamiere-001', 'c-pua-001', 'c-delossantos-001', 'c-barien-001', 'c-navis-001', 'c-pinzon-001', 'c-pablo-001', 'c-base-001', 'c-montilla-001', 'c-paraiso-001', 'c-lasam-kikos-001', 'c-guzman-001', 'c-andres-001'
));

DELETE FROM public.case_activity
WHERE case_id IN (SELECT id FROM public.cases WHERE code NOT IN (
  'c-usigan-001', 'c-baculi-001', 'c-lasam-lakas-001', 'c-collado-001', 'c-yapit-001', 'c-carabacan-001', 'c-magana-001', 'c-mangaoang-001', 'c-chavez-001', 'c-ranjo-001', 'c-coloma-001', 'c-rosendo-001', 'c-mamauag-001', 'c-colobong-001', 'c-pagunuran-001', 'c-massalang-001', 'c-cruz-001', 'c-tumbali-001', 'c-abalos-001', 'c-cubacub-001', 'c-villanueva-001', 'c-galapon-001', 'c-tomas-001', 'c-domingo-001', 'c-uy-001', 'c-duerme-001', 'c-khong-001', 'c-garcia-001', 'c-dimaculangan-001', 'c-mallare-001', 'c-lamiere-001', 'c-pua-001', 'c-delossantos-001', 'c-barien-001', 'c-navis-001', 'c-pinzon-001', 'c-pablo-001', 'c-base-001', 'c-montilla-001', 'c-paraiso-001', 'c-lasam-kikos-001', 'c-guzman-001', 'c-andres-001'
));

DELETE FROM public.case_files
WHERE case_id IN (SELECT id FROM public.cases WHERE code NOT IN (
  'c-usigan-001', 'c-baculi-001', 'c-lasam-lakas-001', 'c-collado-001', 'c-yapit-001', 'c-carabacan-001', 'c-magana-001', 'c-mangaoang-001', 'c-chavez-001', 'c-ranjo-001', 'c-coloma-001', 'c-rosendo-001', 'c-mamauag-001', 'c-colobong-001', 'c-pagunuran-001', 'c-massalang-001', 'c-cruz-001', 'c-tumbali-001', 'c-abalos-001', 'c-cubacub-001', 'c-villanueva-001', 'c-galapon-001', 'c-tomas-001', 'c-domingo-001', 'c-uy-001', 'c-duerme-001', 'c-khong-001', 'c-garcia-001', 'c-dimaculangan-001', 'c-mallare-001', 'c-lamiere-001', 'c-pua-001', 'c-delossantos-001', 'c-barien-001', 'c-navis-001', 'c-pinzon-001', 'c-pablo-001', 'c-base-001', 'c-montilla-001', 'c-paraiso-001', 'c-lasam-kikos-001', 'c-guzman-001', 'c-andres-001'
));

-- Delete extra case rows (old test data, duplicates, wrong codes)
DELETE FROM public.cases
WHERE code NOT IN (
  'c-usigan-001', 'c-baculi-001', 'c-lasam-lakas-001', 'c-collado-001', 'c-yapit-001', 'c-carabacan-001', 'c-magana-001', 'c-mangaoang-001', 'c-chavez-001', 'c-ranjo-001', 'c-coloma-001', 'c-rosendo-001', 'c-mamauag-001', 'c-colobong-001', 'c-pagunuran-001', 'c-massalang-001', 'c-cruz-001', 'c-tumbali-001', 'c-abalos-001', 'c-cubacub-001', 'c-villanueva-001', 'c-galapon-001', 'c-tomas-001', 'c-domingo-001', 'c-uy-001', 'c-duerme-001', 'c-khong-001', 'c-garcia-001', 'c-dimaculangan-001', 'c-mallare-001', 'c-lamiere-001', 'c-pua-001', 'c-delossantos-001', 'c-barien-001', 'c-navis-001', 'c-pinzon-001', 'c-pablo-001', 'c-base-001', 'c-montilla-001', 'c-paraiso-001', 'c-lasam-kikos-001', 'c-guzman-001', 'c-andres-001'
);

-- Delete duplicate report numbers if any slipped through (keep official code only)
DELETE FROM public.cases c
USING public.cases d
WHERE c.report_case_number = d.report_case_number
  AND c.report_case_number BETWEEN 1 AND 43
  AND c.id <> d.id
  AND c.code NOT IN ('c-usigan-001', 'c-baculi-001', 'c-lasam-lakas-001', 'c-collado-001', 'c-yapit-001', 'c-carabacan-001', 'c-magana-001', 'c-mangaoang-001', 'c-chavez-001', 'c-ranjo-001', 'c-coloma-001', 'c-rosendo-001', 'c-mamauag-001', 'c-colobong-001', 'c-pagunuran-001', 'c-massalang-001', 'c-cruz-001', 'c-tumbali-001', 'c-abalos-001', 'c-cubacub-001', 'c-villanueva-001', 'c-galapon-001', 'c-tomas-001', 'c-domingo-001', 'c-uy-001', 'c-duerme-001', 'c-khong-001', 'c-garcia-001', 'c-dimaculangan-001', 'c-mallare-001', 'c-lamiere-001', 'c-pua-001', 'c-delossantos-001', 'c-barien-001', 'c-navis-001', 'c-pinzon-001', 'c-pablo-001', 'c-base-001', 'c-montilla-001', 'c-paraiso-001', 'c-lasam-kikos-001', 'c-guzman-001', 'c-andres-001');

-- Clear remarks on the official 43 before fresh verbatim insert
DELETE FROM public.case_status_updates
WHERE case_id IN (SELECT id FROM public.cases WHERE code IN ('c-usigan-001', 'c-baculi-001', 'c-lasam-lakas-001', 'c-collado-001', 'c-yapit-001', 'c-carabacan-001', 'c-magana-001', 'c-mangaoang-001', 'c-chavez-001', 'c-ranjo-001', 'c-coloma-001', 'c-rosendo-001', 'c-mamauag-001', 'c-colobong-001', 'c-pagunuran-001', 'c-massalang-001', 'c-cruz-001', 'c-tumbali-001', 'c-abalos-001', 'c-cubacub-001', 'c-villanueva-001', 'c-galapon-001', 'c-tomas-001', 'c-domingo-001', 'c-uy-001', 'c-duerme-001', 'c-khong-001', 'c-garcia-001', 'c-dimaculangan-001', 'c-mallare-001', 'c-lamiere-001', 'c-pua-001', 'c-delossantos-001', 'c-barien-001', 'c-navis-001', 'c-pinzon-001', 'c-pablo-001', 'c-base-001', 'c-montilla-001', 'c-paraiso-001', 'c-lasam-kikos-001', 'c-guzman-001', 'c-andres-001'));

-- =============================================================================
-- PHASE 2: MERGE (UPSERT) cases 1–43
-- ON CONFLICT (code) DO UPDATE = merge into existing row if code already exists
-- =============================================================================

-- CASE #1: Republic of the Philippines, rep. by DOST-RO2 v. Florendo R. Usigan
INSERT INTO public.cases (
  code, case_title, case_number, case_type, court, parties, status,
  remarks, report_case_number, filing_date, last_updated
) VALUES (
  'c-usigan-001',
  'Republic of the Philippines, rep. by DOST-RO2 v. Florendo R. Usigan',
  'Civil Case No. 8851',
  'Civil Case',
  'RTC Branch 2, Tuguegarao City, Cagayan',
  'Plaintiff: Republic of the Philippines, rep. by DOST-RO2; Defendant: Florendo R. Usigan',
  'Ongoing'::public.case_status,
  'JANUARY 2023 – JUNE 2023: Attended the hearing on February 2, 2023.',
  1,
  '2023-01-01',
  '2025-12-05'
) ON CONFLICT (code) DO UPDATE SET
  case_title = EXCLUDED.case_title,
  case_number = EXCLUDED.case_number,
  case_type = EXCLUDED.case_type,
  court = EXCLUDED.court,
  parties = EXCLUDED.parties,
  status = EXCLUDED.status,
  remarks = EXCLUDED.remarks,
  report_case_number = EXCLUDED.report_case_number,
  filing_date = EXCLUDED.filing_date,
  last_updated = EXCLUDED.last_updated;

-- PHASE 3: INSERT verbatim Status/Remarks
INSERT INTO public.case_status_updates (case_id, sort_order, body)
SELECT c.id, v.sort_order, v.body
FROM public.cases c
CROSS JOIN (VALUES
  (1, 'JANUARY 2023 – JUNE 2023: Attended the hearing on February 2, 2023.'),
  (2, 'Attended the hearing on March 16, 2023.'),
  (3, 'Received Constancia dated April 28, 2023 on June 7, 2023 resetting the Pre-Trial Conference on June 16, 2023 at 8:30 A.M.'),
  (4, 'Upon communication of the OIC Clerk of Court, Pre-Trial Conference on June 16, 2023 was cancelled and reset to July 20, 2023 at 8:30 AM.'),
  (5, 'JULY 2023 – DECEMBER 2023: Attended the hearing on July 20, 2023.'),
  (6, 'On August 8, 2023, the OSG received an Order dated July 20, 2023, resetting the hearing to September 14, 2023 at 8:30 in the morning.'),
  (7, 'Attended the hearing on September 14, 2023.'),
  (8, 'Under the Order dated September 14, 2023, the court noted the attendance of both counsels; defendant was not present and was indisposed. Plaintiff''s counsel manifested that she would talk with the defendant''s daughter regarding possible settlement.'),
  (9, 'Pre-Trial was set to November 15, 2023.'),
  (10, 'Attended the pre-trial on November 15, 2023.'),
  (11, 'For the presentation of Ms. Lydia Turingan, plaintiff''s first witness, on December 4, 2023.'),
  (12, 'JANUARY 2024 – AUGUST 2024: Presented witnesses Lydia B. Turingan and Nancy C. Guimmayen on December 4, 2023 and January 23, 2024, respectively.'),
  (13, 'Filed on January 29, 2024 a Motion for Marking and Formal Offer of Evidence dated January 26, 2024.'),
  (14, 'Received an Order dated February 14, 2024, which granted the marking of the Judicial Affidavits of the witnesses and admitted plaintiff''s exhibits.'),
  (15, 'Received an Order dated February 27, 2024 resetting the presentation of defendant''s evidence on April 11, 2024 as previously scheduled due to the Conference in PhilJA Training Center, Tagaytay City to be attended by the Judge.'),
  (16, 'Presentation of evidence on April 11, 2024 was waived by the defendant.'),
  (17, 'Under Order dated May 16, 2024, the presentation of defendant''s evidence was reset to June 11, 2024 in view of the absence of plaintiff''s counsel.'),
  (18, 'Filed a Manifestation and Motion clarifying that the absence of plaintiff''s counsel was due to information relayed by DOST-RO2 staff from defendant''s counsel that she would seek cancellation of the hearing due to the absence of Judicial Affidavit of a witness.'),
  (19, 'Under Order dated June 3, 2024, the Court ordered defendant''s counsel to furnish plaintiff''s counsel a copy of the Judicial Affidavit of her witness at least three days prior to the next hearing.'),
  (20, 'The June 11, 2024 hearing was cancelled by the Court.'),
  (21, 'Received from DOST-RO2 a copy of defendant''s JA. On July 11, 2024, an email request was sent to Engr. Magora in order for the OSG to prepare for the conduct of cross-examination of Florendo Usigan.'),
  (22, 'Attended meeting via Google Meet on July 29, 2024 in preparation of the cross-examination of Usigan.'),
  (23, 'Attended the hearing on July 30, 2024, which was reset to September 16, 2024 due to the unavailability of Usigan.'),
  (24, 'SEPTEMBER 2024 – OCTOBER 2024: Attended the September 16, 2024 Hearing.'),
  (25, 'Attended the October 17, 2024 Hearing.'),
  (26, 'Next scheduled hearing for the presentation of defendant''s last witness is set on December 12, 2024 at 8:30 A.M.'),
  (27, 'NOVEMBER 2024 – DECEMBER 2024: Filed a Manifestation and Motion relative to the December 12, 2024 hearing in view of the information relayed by the PAO counsel that defendant has no witness to present on said hearing date.'),
  (28, 'Awaiting a copy of the Court''s Order.'),
  (29, 'Note: May we request the RPMO to check with the court staff the available hearing dates for next year for the purpose of scheduling the hearing dates for DOST-RO2''s rebuttal witnesses. The OSG will provide two dates when it files a Comment on defendant''s FOE.'),
  (30, 'JANUARY 2025 – MARCH 2025: Received defendant''s Formal Offer of Evidence (FOE) on January 6, 2025 and thereafter filed on January 14, 2025 a Comment thereon.'),
  (31, 'Discussed with RPMO the possible rebuttal witness/es to be presented and the timeline of the taking of Judicial Affidavit (JA) until submission to the trial court.'),
  (32, 'Received on February 11, 2025 an Order resolving defendant''s formal offer of evidence and setting the presentation of rebuttal evidence on March 3 and 27, 2025. Under said Order, defendant''s Exhibits "1", "4" to "7", "10", "13" and "15" were admitted in evidence, while Exhibits "2", "3" (Certification of Lucio Calimag), "8", "11" and "14" were not admitted.'),
  (33, 'Attended virtual meetings with Clarenet Balderas in preparation for the taking of her JA.'),
  (34, 'Took the JA of Clarenet Balderas through videoconference and thereafter electronically filed the same before the Court under Submission dated February 25, 2025.'),
  (35, 'Conducted briefing with Clarenet Balderas on March 2, 2025 and presented her as a witness during the March 3, 2025 hearing.'),
  (36, 'Took the JA of Mary Ann Carpiso through videoconference and thereafter electronically filed the same before the Court under Submission dated March 19, 2025.'),
  (37, 'Conducted briefing with Mary Ann Carpiso and presented her as a witness during the March 27, 2025 hearing.'),
  (38, 'Electronically filed a Formal Offer of Rebuttal Evidence on March 31, 2025.'),
  (39, 'APRIL 2025 – MAY 2025: Electronically filed a Memorandum on May 21, 2025.'),
  (40, 'Under Order dated May 28, 2025, the case is now submitted for resolution.'),
  (41, 'JUNE 2025 – DECEMBER 2025: Filed a Notice of Appeal on December 5, 2025.')
) AS v(sort_order, body)
WHERE c.code = 'c-usigan-001';

-- CASE #2: Republic of the Philippines, rep. by DOST-RO2 v. Francisco T. Baculi
INSERT INTO public.cases (
  code, case_title, case_number, case_type, court, parties, status,
  remarks, report_case_number, filing_date, last_updated
) VALUES (
  'c-baculi-001',
  'Republic of the Philippines, rep. by DOST-RO2 v. Francisco T. Baculi',
  'Civil Case No. 8852',
  'Civil Case',
  'RTC Branch 5, Tuguegarao City, Cagayan',
  'Plaintiff: Republic of the Philippines, rep. by DOST-RO2; Defendant: Francisco T. Baculi',
  'Pending'::public.case_status,
  'JANUARY 2023 – JUNE 2023: On November 29, 2022, the OSG received a copy of Order dated November 4, 2022 which states: “the Motion for Reconsideration filed by the defendant, thru counsel is submitted for resolution.”',
  2,
  '2022-01-01',
  '2024-01-01'
) ON CONFLICT (code) DO UPDATE SET
  case_title = EXCLUDED.case_title,
  case_number = EXCLUDED.case_number,
  case_type = EXCLUDED.case_type,
  court = EXCLUDED.court,
  parties = EXCLUDED.parties,
  status = EXCLUDED.status,
  remarks = EXCLUDED.remarks,
  report_case_number = EXCLUDED.report_case_number,
  filing_date = EXCLUDED.filing_date,
  last_updated = EXCLUDED.last_updated;

-- PHASE 3: INSERT verbatim Status/Remarks
INSERT INTO public.case_status_updates (case_id, sort_order, body)
SELECT c.id, v.sort_order, v.body
FROM public.cases c
CROSS JOIN (VALUES
  (1, 'JANUARY 2023 – JUNE 2023: On November 29, 2022, the OSG received a copy of Order dated November 4, 2022 which states: “the Motion for Reconsideration filed by the defendant, thru counsel is submitted for resolution.”'),
  (2, 'Awaiting the resolution of defendant''s Motion for Reconsideration.'),
  (3, 'JULY 2023 – DECEMBER 2023: On August 18, 2023, the OSG received a copy of the Order dated August 4, 2023, denying defendant''s motion for reconsideration. The decision dated September 16, 2022 stands.'),
  (4, 'Received information that Mr. Francisco T. Baculi had already passed away, although no notice of death was filed by his counsel.'),
  (5, 'JANUARY 2024 – AUGUST 2024: On August 18, 2023, the OSG received a copy of the Order dated August 4, 2023, denying defendant''s motion for reconsideration. The decision dated September 16, 2022 stands.'),
  (6, 'Received information that Mr. Francisco T. Baculi had already passed away, although no notice of death was filed by his counsel.'),
  (7, 'During a meeting in the RPMO office that was attended by ARD Sylvia Lacambra, PDs and their staff, which was documented by Engr. Magora, the Cagayan PSTO was tasked to do something after the disclosure and inquiry of PD Nora Garcia relating to the death of Baculi.'),
  (8, 'Awaiting information from Cagayan PSTO.')
) AS v(sort_order, body)
WHERE c.code = 'c-baculi-001';

-- CASE #3: Republic of the Philippines, rep. by DOST-RO2 v. Jose B. Lasam, Jr. (L
INSERT INTO public.cases (
  code, case_title, case_number, case_type, court, parties, status,
  remarks, report_case_number, filing_date, last_updated
) VALUES (
  'c-lasam-lakas-001',
  'Republic of the Philippines, rep. by DOST-RO2 v. Jose B. Lasam, Jr. (Lakas Abono 2000)',
  'Civil Case No. 8853',
  'Civil Case',
  'RTC-Branch 3, Tuguegarao City, Cagayan',
  'Plaintiff: Republic of the Philippines, rep. by DOST-RO2; Defendant: Jose B. Lasam, Jr. (Lakas Abono 2000)',
  'Ongoing'::public.case_status,
  'JANUARY 2023 – JUNE 2023: Received Order dated August 19, 2022 on March 15, 2023, granting the Motion for Execution and directing the issuance of a Writ of Execution.',
  3,
  '2022-01-01',
  '2024-12-03'
) ON CONFLICT (code) DO UPDATE SET
  case_title = EXCLUDED.case_title,
  case_number = EXCLUDED.case_number,
  case_type = EXCLUDED.case_type,
  court = EXCLUDED.court,
  parties = EXCLUDED.parties,
  status = EXCLUDED.status,
  remarks = EXCLUDED.remarks,
  report_case_number = EXCLUDED.report_case_number,
  filing_date = EXCLUDED.filing_date,
  last_updated = EXCLUDED.last_updated;

-- PHASE 3: INSERT verbatim Status/Remarks
INSERT INTO public.case_status_updates (case_id, sort_order, body)
SELECT c.id, v.sort_order, v.body
FROM public.cases c
CROSS JOIN (VALUES
  (1, 'JANUARY 2023 – JUNE 2023: Received Order dated August 19, 2022 on March 15, 2023, granting the Motion for Execution and directing the issuance of a Writ of Execution.'),
  (2, 'Upon information of the letter issued by the Sheriff, the OSG sent Letter dated May 18, 2023 to Sheriff Jojo S. Garcia, informing him of the payment made by defendant Lasam.'),
  (3, 'JULY 2023 – DECEMBER 2023: Upon information of the letter issued by the Sheriff, the OSG sent Letter dated May 18, 2023 to Sheriff Jojo S. Garcia, informing him of the payment made by defendant Lasam.'),
  (4, 'Awaiting reply from the Sheriff regarding the May 18, 2023 OSG Letter. (The DOST-RO2 may wish to follow-up with the Sheriff).'),
  (5, 'SEPTEMBER 2024 – OCTOBER 2024: Received from DOST-RO2 on October 4, 2024 a copy of Sheriff''s Report with Manifestation.'),
  (6, 'Conducted a meeting in the afternoon of October 4, 2024 via MS Teams to discuss the Sheriff''s Report and whether DOST-RO2 will proceed with the implementation with the Writ of Execution.'),
  (7, 'Received from DOST-RO2 the RTC''s Order dated October 1, 2024, ordering plaintiff to manifest within 15 days if it reduced its claim to the principal sum so that the Court no longer pursue execution and require deposit of fees.'),
  (8, 'Filed a Manifestation dated October 15, 2024 attaching the official receipt for the payment of the Itemized Estimated Amount of Expenses for the Writ of Execution.'),
  (9, 'State Solicitor Ramos already talked with the Sheriff regarding the payment of the expenses and the ensuing implementation of the writ of execution. SETUP Manager Mary Ann Carpiso was also introduced to Sheriff Jojo Garcia for coordination purposes.'),
  (10, 'NOVEMBER 2024 – DECEMBER 2024: Received on December 3, 2024 the Court''s October 18, 2024 Order noting the plaintiff''s Manifestation dated October 15, 2024 with proof of payment of the estimated amount of expenses in the implementation of the Writ of Execution. Accordingly, the Sheriff can proceed with the execution.'),
  (11, 'Note: For RPMO''s monitoring.')
) AS v(sort_order, body)
WHERE c.code = 'c-lasam-lakas-001';

-- CASE #4: Republic of the Philippines, rep. by DOST-RO2 v. Benjamin Joseph D. Co
INSERT INTO public.cases (
  code, case_title, case_number, case_type, court, parties, status,
  remarks, report_case_number, filing_date, last_updated
) VALUES (
  'c-collado-001',
  'Republic of the Philippines, rep. by DOST-RO2 v. Benjamin Joseph D. Collado, III (Lucille Tree Farm)',
  'Civil Case No. 8854',
  'Civil Case',
  'RTC-Branch 1, Tuguegarao City, Cagayan',
  'Plaintiff: Republic of the Philippines, rep. by DOST-RO2; Defendant: Benjamin Joseph D. Collado, III (Lucille Tree Farm)',
  'Archived'::public.case_status,
  'JANUARY 2023 – JUNE 2023: Received Order dated July 9, 2021 on September 28, 2021, which archived the case pending information on correct address/exact whereabouts of Mr. Collado.',
  4,
  '2021-01-01',
  '2021-09-28'
) ON CONFLICT (code) DO UPDATE SET
  case_title = EXCLUDED.case_title,
  case_number = EXCLUDED.case_number,
  case_type = EXCLUDED.case_type,
  court = EXCLUDED.court,
  parties = EXCLUDED.parties,
  status = EXCLUDED.status,
  remarks = EXCLUDED.remarks,
  report_case_number = EXCLUDED.report_case_number,
  filing_date = EXCLUDED.filing_date,
  last_updated = EXCLUDED.last_updated;

-- PHASE 3: INSERT verbatim Status/Remarks
INSERT INTO public.case_status_updates (case_id, sort_order, body)
SELECT c.id, v.sort_order, v.body
FROM public.cases c
CROSS JOIN (VALUES
  (1, 'JANUARY 2023 – JUNE 2023: Received Order dated July 9, 2021 on September 28, 2021, which archived the case pending information on correct address/exact whereabouts of Mr. Collado.'),
  (2, 'JULY 2023 – DECEMBER 2023: Received Order dated July 9, 2021 on September 28, 2021, which archived the case pending information on correct address/exact whereabouts of Mr. Collado.'),
  (3, 'JANUARY 2024 – AUGUST 2024: Received Order dated July 9, 2021 on September 28, 2021, which archived the case pending information on correct address/exact whereabouts of Mr. Collado.'),
  (4, 'Awaiting from DOST-RO2 the aforesaid correct address/exact whereabouts of Mr. Collado.')
) AS v(sort_order, body)
WHERE c.code = 'c-collado-001';

-- CASE #5: Republic of the Philippines, rep. by DOST-RO2 v. Rogelio T. Yapit (R.T
INSERT INTO public.cases (
  code, case_title, case_number, case_type, court, parties, status,
  remarks, report_case_number, filing_date, last_updated
) VALUES (
  'c-yapit-001',
  'Republic of the Philippines, rep. by DOST-RO2 v. Rogelio T. Yapit (R.T. Yapit Enterprises)',
  'Civil Case No. 8855',
  'Civil Case',
  'RTC-Branch 3, Tuguegarao City, Cagayan',
  'Plaintiff: Republic of the Philippines, rep. by DOST-RO2; Defendant: Rogelio T. Yapit (R.T. Yapit Enterprises)',
  'Ongoing'::public.case_status,
  'JANUARY 2023 – JUNE 2023: Attended the hearing on February 2, 2023 at 8:30 A.M.',
  5,
  '2023-01-01',
  '2024-11-26'
) ON CONFLICT (code) DO UPDATE SET
  case_title = EXCLUDED.case_title,
  case_number = EXCLUDED.case_number,
  case_type = EXCLUDED.case_type,
  court = EXCLUDED.court,
  parties = EXCLUDED.parties,
  status = EXCLUDED.status,
  remarks = EXCLUDED.remarks,
  report_case_number = EXCLUDED.report_case_number,
  filing_date = EXCLUDED.filing_date,
  last_updated = EXCLUDED.last_updated;

-- PHASE 3: INSERT verbatim Status/Remarks
INSERT INTO public.case_status_updates (case_id, sort_order, body)
SELECT c.id, v.sort_order, v.body
FROM public.cases c
CROSS JOIN (VALUES
  (1, 'JANUARY 2023 – JUNE 2023: Attended the hearing on February 2, 2023 at 8:30 A.M.'),
  (2, 'Sent Letter dated February 21, 2022 on February 22, 2023 re: proposed settlement of the case.'),
  (3, 'Attended the hearing on March 16, 2023.'),
  (4, 'Drafted Compromise Agreement.'),
  (5, 'Made follow-ups (with DOST-RO2 and Atty. Genevie Ogalino) regarding the status of the signing of the Compromise Agreement.'),
  (6, 'Received Constancia dated April 28, 2023 on June 7, 2023. Pre-Trial Conference was reset to June 16, 2023 at 8:30 A.M.'),
  (7, 'On June 5, 2023, Atty. Ogalino gave an update that Mr. Yapit will go to the DOST-RO2 office within the week and sign the Agreement.'),
  (8, 'Upon communication of the OIC Clerk of Court, Pre-Trial Conference on June 16, 2023 was cancelled and reset to July 20, 2023 at 8:30 AM.'),
  (9, 'JULY 2023 – DECEMBER 2023: Attended the pre-trial on July 20, 2023.'),
  (10, 'Received the July 20, 2023 Pre-Trial Order on September 19, 2023.'),
  (11, 'Attended the hearing on September 14, 2023.'),
  (12, 'Received the September 14, 2023 Order on September 29, 2023, which reset the hearing to November 15, 2023 at 8:30 A.M.'),
  (13, 'Sent October 9, 2023 Letter to Director Bilgera regarding the September 27, 2023 letter of Atty. Genevieve Ogalino on the proposed settlement of the case.'),
  (14, 'Attended the hearing on November 15, 2023. Defendant''s counsel manifested that they would await the Commission on Audit (COA) action regarding the Compromise Agreement; if the request is denied, Mr. Yapit is willing to pay the remaining balance in installments. DOST-RO2 should immediately notify the OSG regarding COA''s action.'),
  (15, 'JANUARY 2024 – AUGUST 2024: Received on January 19, 2024 a Motion to Reset the Scheduled Date of Hearing dated January 11, 2024 from Atty. Ogalino.'),
  (16, 'Attended the Hearing on January 23, 2024.'),
  (17, 'Received on February 2, 2024 an Order dated January 23, 2024, resetting the hearing to March 7, 2024 at 8:30 A.M.'),
  (18, 'Received on March 11, 2024 a Motion from Atty. Ogalino dated March 4, 2024 to reset the March 7, 2024 hearing.'),
  (19, 'Received on March 12, 2024 an Order dated February 27, 2024 resetting the March 7, 2024 hearing to April 23, 2024 at 8:30 A.M.'),
  (20, 'Filed a Motion to Reset Hearing on April 18, 2024 for the April 23, 2024 hearing.'),
  (21, 'Received on May 13, 2024 an Order dated April 23, 2024, resetting the hearing to May 23, 2024 at 8:30 A.M.'),
  (22, 'Filed Motion to Reset Hearing on May 21, 2024 for the May 23, 2024 hearing.'),
  (23, 'Received on June 4, 2024 an Order dated May 23, 2024, resetting the hearing to July 15, 2024 at 8:30 A.M.'),
  (24, 'Received letter dated June 19, 2024 from Atty. Ogalino regarding the settlement of the case.'),
  (25, 'This was referred to the DOST-RO2 for update in the email dated July 3, 2024 in view of the July 15, 2024 hearing.'),
  (26, 'Filed Motion to Reset Hearing on July 12, 2024 for the July 15, 2024 hearing.'),
  (27, 'Received Order dated July 15, 2024, resetting the hearing to July 30, 2024 at 8:30 A.M.'),
  (28, 'Attended the hearing on July 30, 2024.'),
  (29, 'Received on August 13, 2024 the Order dated July 30, 2024, resetting the case on September 16, 2024 at 8:30 A.M.'),
  (30, 'Received via email from Atty. Ogalino on August 19, 2024 a Letter regarding the intent to settle the case and a draft of the Compromise Agreement. This was forwarded to the DOST-RO2 on August 20, 2024 via email.'),
  (31, 'Sent Atty. Ogalino and the DOST-RO2 a draft of the Compromise Agreement via email, for review and comments. Instructions regarding the finalization/signing of the Compromise Agreement were discussed during the August 21, 2024 meeting.'),
  (32, 'The hearing is scheduled on September 16, 2024 at 8:30 A.M.'),
  (33, 'SEPTEMBER 2024 – OCTOBER 2024: Discussed the finalization of the Compromise Agreement via Messenger group call (meeting with the presence of PSTO Cagayan).'),
  (34, 'Coordinated with Atty. Ogalino with respect to the delivery of the checks and the finalization of the Compromise Agreement.'),
  (35, 'Attended the September 16, 2024 Hearing.'),
  (36, 'Attended the October 17, 2024 Hearing.'),
  (37, 'Filed the Motion for Approval of the Compromise Agreement on October 22, 2024.'),
  (38, 'The Status Hearing regarding the submission of the Compromise Agreement is set on December 12, 2024.'),
  (39, 'NOVEMBER 2024 – DECEMBER 2024: Received on November 26, 2024 the Judgment Based on Compromise dated November 13, 2024.'),
  (40, 'Note: The DOST-RO2 is reminded to see to it that the agreed terms of the Compromise Agreement are followed especially with respect to its undertakings, particularly on the provision of technical assistance and guidance based on the Technology Needs Assessment.')
) AS v(sort_order, body)
WHERE c.code = 'c-yapit-001';

-- CASE #6: Republic of the Philippines, rep. by DOST-RO2 v. Edwin P. Carabbacan, 
INSERT INTO public.cases (
  code, case_title, case_number, case_type, court, parties, status,
  remarks, report_case_number, filing_date, last_updated
) VALUES (
  'c-carabacan-001',
  'Republic of the Philippines, rep. by DOST-RO2 v. Edwin P. Carabbacan, Jr. (EPC 8 Iron Works)',
  'Civil Case No. 8856',
  'Civil Case',
  'RTC-Branch 10, Tuguegarao City, Cagayan',
  'Plaintiff: Republic of the Philippines, rep. by DOST-RO2; Defendant: Edwin P. Carabbacan, Jr. (EPC 8 Iron Works)',
  'Ongoing'::public.case_status,
  'JANUARY 2023 – JUNE 2023: For filing of Motion for Issuance of Writ of Execution, provided that defendant has received a copy of the decision and failed to file any motion for reconsideration or notice of appeal within 15 days therefrom.',
  6,
  '2023-01-01',
  '2024-09-16'
) ON CONFLICT (code) DO UPDATE SET
  case_title = EXCLUDED.case_title,
  case_number = EXCLUDED.case_number,
  case_type = EXCLUDED.case_type,
  court = EXCLUDED.court,
  parties = EXCLUDED.parties,
  status = EXCLUDED.status,
  remarks = EXCLUDED.remarks,
  report_case_number = EXCLUDED.report_case_number,
  filing_date = EXCLUDED.filing_date,
  last_updated = EXCLUDED.last_updated;

-- PHASE 3: INSERT verbatim Status/Remarks
INSERT INTO public.case_status_updates (case_id, sort_order, body)
SELECT c.id, v.sort_order, v.body
FROM public.cases c
CROSS JOIN (VALUES
  (1, 'JANUARY 2023 – JUNE 2023: For filing of Motion for Issuance of Writ of Execution, provided that defendant has received a copy of the decision and failed to file any motion for reconsideration or notice of appeal within 15 days therefrom.'),
  (2, 'JANUARY 2024 – AUGUST 2024: The hearing is scheduled on September 16, 2024 at 8:30 A.M.'),
  (3, 'For filing of Motion for Issuance of Writ of Execution, provided that defendant has received a copy of the Decision and failed to file any motion for reconsideration or notice of appeal within 15 days therefrom.'),
  (4, 'For checking in the RTC records by DOST-RO2 regarding defendant''s receipt of the Decision or if any motion for reconsideration or notice of appeal was filed by defendant. If there is none, DOST-RO2 to secure Certificate of Finality and refer to the OSG for the finalization of the Motion for Issuance of Writ of Execution.'),
  (5, 'Please note that this was earlier referred to Ma''am Lydia.')
) AS v(sort_order, body)
WHERE c.code = 'c-carabacan-001';

-- CASE #7: Republic of the Philippines, rep. by DOST-RO2 v. Spouses Reymund Y. Ma
INSERT INTO public.cases (
  code, case_title, case_number, case_type, court, parties, status,
  remarks, report_case_number, filing_date, last_updated
) VALUES (
  'c-magana-001',
  'Republic of the Philippines, rep. by DOST-RO2 v. Spouses Reymund Y. Magana and Monaliza T. Magana',
  'Civil Case No. 9350',
  'Civil Case',
  'RTC-Branch 3, Tuguegarao City, Cagayan',
  'Plaintiff: Republic of the Philippines, rep. by DOST-RO2; Defendant: Spouses Reymund Y. Magana and Monaliza T. Magana',
  'Ongoing'::public.case_status,
  'JANUARY 2023 – JUNE 2023: Complaint with Judicial Affidavits already filed with the court.',
  7,
  '2023-01-01',
  '2025-05-21'
) ON CONFLICT (code) DO UPDATE SET
  case_title = EXCLUDED.case_title,
  case_number = EXCLUDED.case_number,
  case_type = EXCLUDED.case_type,
  court = EXCLUDED.court,
  parties = EXCLUDED.parties,
  status = EXCLUDED.status,
  remarks = EXCLUDED.remarks,
  report_case_number = EXCLUDED.report_case_number,
  filing_date = EXCLUDED.filing_date,
  last_updated = EXCLUDED.last_updated;

-- PHASE 3: INSERT verbatim Status/Remarks
INSERT INTO public.case_status_updates (case_id, sort_order, body)
SELECT c.id, v.sort_order, v.body
FROM public.cases c
CROSS JOIN (VALUES
  (1, 'JANUARY 2023 – JUNE 2023: Complaint with Judicial Affidavits already filed with the court.'),
  (2, 'JANUARY 2024 – AUGUST 2024: Pending verification as to whether defendant filed an Answer. OSG received on July 11, 2024 an Order dated June 28, 2024, dismissing the case without prejudice on the ground of plaintiff''s failure to prosecute.'),
  (3, 'Prepared an Omnibus Motion dated July 17, 2024, praying that the Court declare defendant in default and thereafter render judgment granting to plaintiff the relief prayed for in its Complaint.'),
  (4, 'Under letter dated July 17, 2024, the DOST-RO2 requested to personally serve and file said Omnibus Motion on or before July 26, 2024. Considering that the request cannot be accomplished before the due date, the OSG served and filed on July 26, 2024 the Omnibus Motion via registered mail.'),
  (5, 'SEPTEMBER 2024 – OCTOBER 2024: Filed a Manifestation and Motion dated September 18, 2024 on September 19, 2024.'),
  (6, 'Sent an email outlining the instructions for the September 20, 2024 Hearing.'),
  (7, 'Attended the October 17, 2024 Hearing.'),
  (8, 'Next scheduled hearing (ex parte presentation of evidence/witnesses before the Branch Clerk of Court) is on December 5, 2024 at 1:00 P.M.'),
  (9, 'NOVEMBER 2024 – DECEMBER 2024: Attended the ex parte hearing on December 5, 2024 in the afternoon, presented two DOST-RO2 witnesses (Daisy Simon and Nancy C. Guimmayen) and formally offered plaintiff''s evidence.'),
  (10, 'Awaiting a copy of the Court''s Order but the case is deemed submitted for resolution.'),
  (11, 'JANUARY 2025 – MARCH 2025: Received on January 7, 2025 an Order admitting plaintiffs'' Exhibits "A" to "W" and thereafter submitting the case for resolution.'),
  (12, 'APRIL 2025 – MAY 2025: Received through email on May 13, 2025 the favorable Judgment in the case.'),
  (13, 'Transmitted a copy thereof, both electronic and physical, to RPMO and RD on May 20 and 21, 2025, respectively.'),
  (14, 'JUNE 2025 – DECEMBER 2025: Transmitted a copy of the Judgment dated March 31, 2025, both electronic and physical, to RPMO and RD on May 20 and 21, 2025, respectively.'),
  (15, 'NOTE: Similar with the cases against Fe Corazon Chavez-Tiongson and Edwin Carabbacan, there is a need for RPMO to check the court record regarding defendant''s receipt of the Judgment or determine whether any motion for reconsideration or notice of appeal was filed by defendant. If defendant has received said Judgment and did not file a motion/notice of appeal, DOST-RO2 should secure a Certificate of Finality and forward it to the OSG for the filing of a Motion for Issuance of Writ of Execution.')
) AS v(sort_order, body)
WHERE c.code = 'c-magana-001';

-- CASE #8: Republic of the Philippines, rep. by DOST-RO2 v. Jesus L. Mangaoang
INSERT INTO public.cases (
  code, case_title, case_number, case_type, court, parties, status,
  remarks, report_case_number, filing_date, last_updated
) VALUES (
  'c-mangaoang-001',
  'Republic of the Philippines, rep. by DOST-RO2 v. Jesus L. Mangaoang',
  'Civil Case No. 9355',
  'Civil Case',
  'RTC-Branch 1, Tuguegarao City, Cagayan',
  'Plaintiff: Republic of the Philippines, rep. by DOST-RO2; Defendant: Jesus L. Mangaoang',
  'Ongoing'::public.case_status,
  'JANUARY 2023 – JUNE 2023: Complaint with Judicial Affidavits already filed with the court.',
  8,
  '2023-01-01',
  '2025-11-06'
) ON CONFLICT (code) DO UPDATE SET
  case_title = EXCLUDED.case_title,
  case_number = EXCLUDED.case_number,
  case_type = EXCLUDED.case_type,
  court = EXCLUDED.court,
  parties = EXCLUDED.parties,
  status = EXCLUDED.status,
  remarks = EXCLUDED.remarks,
  report_case_number = EXCLUDED.report_case_number,
  filing_date = EXCLUDED.filing_date,
  last_updated = EXCLUDED.last_updated;

-- PHASE 3: INSERT verbatim Status/Remarks
INSERT INTO public.case_status_updates (case_id, sort_order, body)
SELECT c.id, v.sort_order, v.body
FROM public.cases c
CROSS JOIN (VALUES
  (1, 'JANUARY 2023 – JUNE 2023: Complaint with Judicial Affidavits already filed with the court.'),
  (2, 'JANUARY 2024 – AUGUST 2024: Prepared an Omnibus Motion dated July 17, 2024, praying that the Court declare defendant in default and thereafter render judgment granting to plaintiff the relief prayed for in its Complaint.'),
  (3, 'SEPTEMBER 2024 – OCTOBER 2024: Attended the September 26, 2024 Hearing.'),
  (4, 'Next scheduled hearing (ex parte presentation of evidence/witnesses before the Branch Clerk of Court) is on December 4, 2024 at 2:00 P.M.'),
  (5, 'NOVEMBER 2024 – DECEMBER 2024: Attended the ex parte hearing on December 4, 2024 in the afternoon, presented two DOST-RO2 witnesses (PD Jonathan del Nuestro and Ma. Angelica Adduru) and formally offered plaintiff''s evidence.'),
  (6, 'Awaiting a copy of the Court''s Order but the case is deemed submitted for resolution.'),
  (7, 'JANUARY 2025 – MARCH 2025: Received Court''s Resolution dated February 10, 2025, which admitted plaintiff''s exhibits and thereafter submitted the case for decision.'),
  (8, 'Received from RPMO an advance copy of Decision dated March 14, 2025.'),
  (9, 'Discussed with RPMO the possible filing of a Motion for Clarification of the Court''s favorable decision.'),
  (10, 'APRIL 2025 – MAY 2025: After discussion with RPMO, a Motion for Clarification of the Court''s favorable decision was electronically filed on April 14, 2025.'),
  (11, 'Received from RPMO a copy of the Notice of Appeal filed by Mangaoang.'),
  (12, 'Attended the May 29, 2025 hearing on the motion for clarification.'),
  (13, 'JUNE 2025 – DECEMBER 2025: Under Order dated July 23, 2025, the RTC has given due course the Notice of Appeal filed by the defendant.'),
  (14, 'On November 6, 2025, the OSG received a copy of the Notice to File Brief dated October 22, 2025, requiring the counsel for defendant-appellant to file Appellant''s Brief within 45 days from notice. Appellee Republic was likewise given the same period from receipt of the appellant''s brief to file its Appellee''s Brief.')
) AS v(sort_order, body)
WHERE c.code = 'c-mangaoang-001';

-- CASE #9: Republic of the Philippines, rep. by DOST-RO2 v. Fe Corazon Chavez-Tio
INSERT INTO public.cases (
  code, case_title, case_number, case_type, court, parties, status,
  remarks, report_case_number, filing_date, last_updated
) VALUES (
  'c-chavez-001',
  'Republic of the Philippines, rep. by DOST-RO2 v. Fe Corazon Chavez-Tiongson',
  'Civil Case No. 3344',
  'Civil Case',
  'Municipal Trial Court in Cities, Branch 01, Tuguegarao City, Cagayan',
  'Plaintiff: Republic of the Philippines, rep. by DOST-RO2; Defendant: Fe Corazon Chavez-Tiongson',
  'Ongoing'::public.case_status,
  'JANUARY 2023 – JUNE 2023: Complaint with Judicial Affidavits already transmitted to DOST-RO2, for filing.',
  9,
  '2023-01-01',
  '2024-07-31'
) ON CONFLICT (code) DO UPDATE SET
  case_title = EXCLUDED.case_title,
  case_number = EXCLUDED.case_number,
  case_type = EXCLUDED.case_type,
  court = EXCLUDED.court,
  parties = EXCLUDED.parties,
  status = EXCLUDED.status,
  remarks = EXCLUDED.remarks,
  report_case_number = EXCLUDED.report_case_number,
  filing_date = EXCLUDED.filing_date,
  last_updated = EXCLUDED.last_updated;

-- PHASE 3: INSERT verbatim Status/Remarks
INSERT INTO public.case_status_updates (case_id, sort_order, body)
SELECT c.id, v.sort_order, v.body
FROM public.cases c
CROSS JOIN (VALUES
  (1, 'JANUARY 2023 – JUNE 2023: Complaint with Judicial Affidavits already transmitted to DOST-RO2, for filing.'),
  (2, 'JANUARY 2024 – AUGUST 2024: Received on November 17, 2023 a Return of Summons/Manifestation dated September 22, 2023.'),
  (3, 'Received on January 12, 2024 a letter from the Clerk of Court regarding the Summons/Manifestation dated September 22, 2023.'),
  (4, 'Filed a Manifestation and Motion dated January 17, 2024 praying that the Court render judgment in favor of the plaintiff.'),
  (5, 'Received on January 24, 2024 a Subpoena to Regional Director Dr. Virginia D. Bilgera to appear in court for the hearing of plaintiff''s Manifestation and Motion on February 16, 2024 at 1:30 P.M.'),
  (6, 'Filed a Supplement to the Manifestation and Motion, praying that plaintiff''s Manifestation and Motion be resolved sans hearing or appearance from RD Bilgera and plaintiff''s counsel.'),
  (7, 'Received on February 2, 2024 an Order dated January 31, 2024 which states that for failure of defendant to file her Answer within the reglementary period from receipt of Summons, judgment will be rendered by the Court pursuant to the Rules on Expedited Procedure.'),
  (8, 'Received on February 27, 2024 a Judgment dated February 20, 2024, which granted the reliefs prayed for plaintiff in its Complaint.'),
  (9, 'Transmitted said Judgment to DOST-RO2 through a letter dated March 4, 2024.'),
  (10, 'Under letter dated July 17, 2024, the DOST-RO2 was requested to personally serve and file the previous Motion.'),
  (11, 'Received information that the Omnibus Motion was filed on July 31, 2024.'),
  (12, 'SEPTEMBER 2024 – OCTOBER 2024: Please see applicable remarks in Carabbacan.'),
  (13, 'NOVEMBER 2024 – DECEMBER 2024: NOTE: Similar with the case against Carabbacan, there is a need for RPMO to check the court record regarding defendant''s receipt of the Judgment or determine whether any motion for reconsideration or notice of appeal was filed by defendant. If defendant has received said Judgment and did not file a motion/notice of appeal, DOST-RO2 should secure a Certificate of Finality and forward it to the OSG for the filing of a Motion for Issuance of Writ of Execution.')
) AS v(sort_order, body)
WHERE c.code = 'c-chavez-001';

-- CASE #10: In the Matter of Petition for Voluntary Rehabilitation Pursuant to R.A
INSERT INTO public.cases (
  code, case_title, case_number, case_type, court, parties, status,
  remarks, report_case_number, filing_date, last_updated
) VALUES (
  'c-ranjo-001',
  'In the Matter of Petition for Voluntary Rehabilitation Pursuant to R.A. 10142 or "The Financial Rehabilitation and Insolvency Act of 2010" of: Sps. Carlo C. Ranjo and Lorelei S. Ranjo',
  'SPL PROC No. 2939',
  'Special Proceeding',
  'RTC-Branch 16, City of Ilagan, Isabela',
  'Republic of the Philippines, rep. by DOST-RO2 vs. In the Matter of Petition for Voluntary Rehabilitation Pursuant to R.A. 10142 or "The Financial Rehabilitation and Insolvency Act of 2010" of: Sps. Carlo C. Ranjo and Lorelei S. Ranjo',
  'Ongoing'::public.case_status,
  'JANUARY 2024 – AUGUST 2024: Conducted meeting last March 13, 2024 via Google Meet attended by PSTO staff and Ms. Nancy Guimmayen.',
  10,
  '2024-01-01',
  '2025-11-13'
) ON CONFLICT (code) DO UPDATE SET
  case_title = EXCLUDED.case_title,
  case_number = EXCLUDED.case_number,
  case_type = EXCLUDED.case_type,
  court = EXCLUDED.court,
  parties = EXCLUDED.parties,
  status = EXCLUDED.status,
  remarks = EXCLUDED.remarks,
  report_case_number = EXCLUDED.report_case_number,
  filing_date = EXCLUDED.filing_date,
  last_updated = EXCLUDED.last_updated;

-- PHASE 3: INSERT verbatim Status/Remarks
INSERT INTO public.case_status_updates (case_id, sort_order, body)
SELECT c.id, v.sort_order, v.body
FROM public.cases c
CROSS JOIN (VALUES
  (1, 'JANUARY 2024 – AUGUST 2024: Conducted meeting last March 13, 2024 via Google Meet attended by PSTO staff and Ms. Nancy Guimmayen.'),
  (2, 'Filed on March 20, 2024 a Comment/Opposition to the Petition dated February 21, 2024.'),
  (3, 'Filed on March 20, 2024 a Notice of Claim.'),
  (4, 'Gave briefing and instructions to ARD Sylvia Lacambra and Mr. Jude Magora in preparation of the April 4, 2024 hearing. Also sent notes via e-mail.'),
  (5, 'Still awaiting for DOST-RO2 to name a nominee for the ad interim rehabilitation receiver, if any.'),
  (6, 'The next hearing is scheduled on September 30, 2024 at 2:00 P.M.'),
  (7, 'Request for meeting prior to the meeting.'),
  (8, 'SEPTEMBER 2024 – OCTOBER 2024: Attended the Hearing on September 30, 2024 at 2:00 P.M.'),
  (9, 'Next scheduled hearing is on December 3, 2024 at 2:00 P.M.'),
  (10, 'Please note the factual determination to be made by Mr. Anzon Babaran anent the SETUP equipment vis-a-vis the other equipment obtained by Lorelei Ranjo from a similar supplier.'),
  (11, 'NOVEMBER 2024 – DECEMBER 2024: Attended the hearing on December 3, 2024 at 2:00 P.M. where the RTC appointed the receiver nominated by the petitioners, as well as ordered petitioners to submit the following: Financial Statement as of December 31, 2023, 2023 Income Tax Return, business permits and licenses.'),
  (12, 'The court-appointed receiver, Atty. Cheryl Arni F. Macutay, CPA, was directed to submit her schedule of professional/receiver fees and for petitioner to furnish the parties a copy thereof for their comment before the next hearing.'),
  (13, 'Note: Once the schedule of fees is received by the OSG, may we request the DOST-RO2, through the RPMO, to give comment on the reasonableness of the amount/s stated therein. The RPMO may inquire with Land Bank.'),
  (14, 'The next scheduled hearing is set on February 27, 2025 at 2:00 P.M.'),
  (15, 'JANUARY 2025 – MARCH 2025: Conducted briefing and gave instructions relative to the scheduled February 27, 2025 hearing.'),
  (16, 'Received Order dated February 24, 2025 resetting the February 27, 2025 hearing to June 3, 2025 at 2:00 p.m.'),
  (17, 'APRIL 2025 – MAY 2025: Travelled to Tuguegarao City on May 29, 2025 for the scheduled June 3, 2025 hearing.'),
  (18, 'JUNE 2025 – DECEMBER 2025: On June 3, 2025, State Solicitor Ramos attended the scheduled hearing.'),
  (19, 'On September 4, 2025, State Solicitor Ramos attended the scheduled hearing.'),
  (20, 'On November 13, 2025, State Solicitor Ramos attended the scheduled hearing.'),
  (21, 'The next scheduled hearing is on March 17, 2026 at 2:00 p.m.')
) AS v(sort_order, body)
WHERE c.code = 'c-ranjo-001';

-- CASE #11: Marivic P. Coloma (Triple M'A Ice Manufacturing)
INSERT INTO public.cases (
  code, case_title, case_number, case_type, court, parties, status,
  remarks, report_case_number, filing_date, last_updated
) VALUES (
  'c-coloma-001',
  'Marivic P. Coloma (Triple M''A Ice Manufacturing)',
  NULL,
  'Pre-litigation',
  NULL,
  'Republic of the Philippines, rep. by DOST-RO2 vs. Marivic P. Coloma',
  'Pending'::public.case_status,
  'No status/remarks text is recorded in the supplied Status/Remarks cells for this entry.',
  11,
  '2023-01-01',
  '2023-01-01'
) ON CONFLICT (code) DO UPDATE SET
  case_title = EXCLUDED.case_title,
  case_number = EXCLUDED.case_number,
  case_type = EXCLUDED.case_type,
  court = EXCLUDED.court,
  parties = EXCLUDED.parties,
  status = EXCLUDED.status,
  remarks = EXCLUDED.remarks,
  report_case_number = EXCLUDED.report_case_number,
  filing_date = EXCLUDED.filing_date,
  last_updated = EXCLUDED.last_updated;

-- PHASE 3: INSERT verbatim Status/Remarks
INSERT INTO public.case_status_updates (case_id, sort_order, body)
SELECT c.id, v.sort_order, v.body
FROM public.cases c
CROSS JOIN (VALUES
  (1, 'No status/remarks text is recorded in the supplied Status/Remarks cells for this entry.')
) AS v(sort_order, body)
WHERE c.code = 'c-coloma-001';

-- CASE #12: Mr. Jonathan Rosendo (Mang Jose Grill and Restaurant)
INSERT INTO public.cases (
  code, case_title, case_number, case_type, court, parties, status,
  remarks, report_case_number, filing_date, last_updated
) VALUES (
  'c-rosendo-001',
  'Mr. Jonathan Rosendo (Mang Jose Grill and Restaurant)',
  NULL,
  'Pre-litigation',
  NULL,
  'Republic of the Philippines, rep. by DOST-RO2 vs. Jonathan Rosendo',
  'Pending'::public.case_status,
  'JANUARY 2023 – JUNE 2023: Sent Demand Letter dated May 5, 2022 on the same day.',
  12,
  '2022-05-05',
  '2022-05-05'
) ON CONFLICT (code) DO UPDATE SET
  case_title = EXCLUDED.case_title,
  case_number = EXCLUDED.case_number,
  case_type = EXCLUDED.case_type,
  court = EXCLUDED.court,
  parties = EXCLUDED.parties,
  status = EXCLUDED.status,
  remarks = EXCLUDED.remarks,
  report_case_number = EXCLUDED.report_case_number,
  filing_date = EXCLUDED.filing_date,
  last_updated = EXCLUDED.last_updated;

-- PHASE 3: INSERT verbatim Status/Remarks
INSERT INTO public.case_status_updates (case_id, sort_order, body)
SELECT c.id, v.sort_order, v.body
FROM public.cases c
CROSS JOIN (VALUES
  (1, 'JANUARY 2023 – JUNE 2023: Sent Demand Letter dated May 5, 2022 on the same day.')
) AS v(sort_order, body)
WHERE c.code = 'c-rosendo-001';

-- CASE #13: Mr. Tomas C. Mamauag (Mamauag Agricultural Supply and Corn Buying Stat
INSERT INTO public.cases (
  code, case_title, case_number, case_type, court, parties, status,
  remarks, report_case_number, filing_date, last_updated
) VALUES (
  'c-mamauag-001',
  'Mr. Tomas C. Mamauag (Mamauag Agricultural Supply and Corn Buying Station)',
  NULL,
  'Pre-litigation',
  NULL,
  'Republic of the Philippines, rep. by DOST-RO2 vs. Tomas C. Mamauag',
  'Pending'::public.case_status,
  'Awaiting further instructions from DOST-RO2.',
  13,
  '2023-01-01',
  '2023-01-01'
) ON CONFLICT (code) DO UPDATE SET
  case_title = EXCLUDED.case_title,
  case_number = EXCLUDED.case_number,
  case_type = EXCLUDED.case_type,
  court = EXCLUDED.court,
  parties = EXCLUDED.parties,
  status = EXCLUDED.status,
  remarks = EXCLUDED.remarks,
  report_case_number = EXCLUDED.report_case_number,
  filing_date = EXCLUDED.filing_date,
  last_updated = EXCLUDED.last_updated;

-- PHASE 3: INSERT verbatim Status/Remarks
INSERT INTO public.case_status_updates (case_id, sort_order, body)
SELECT c.id, v.sort_order, v.body
FROM public.cases c
CROSS JOIN (VALUES
  (1, 'Awaiting further instructions from DOST-RO2.')
) AS v(sort_order, body)
WHERE c.code = 'c-mamauag-001';

-- CASE #14: Mr. Nomer G. Colobong (NG Colobong Tire Surplus Vulcanizing Shop)
INSERT INTO public.cases (
  code, case_title, case_number, case_type, court, parties, status,
  remarks, report_case_number, filing_date, last_updated
) VALUES (
  'c-colobong-001',
  'Mr. Nomer G. Colobong (NG Colobong Tire Surplus Vulcanizing Shop)',
  NULL,
  'Pre-litigation',
  NULL,
  'Republic of the Philippines, rep. by DOST-RO2 vs. Nomer G. Colobong',
  'Pending'::public.case_status,
  'No status/remarks text is recorded in the supplied Status/Remarks cells for this entry.',
  14,
  '2023-01-01',
  '2023-01-01'
) ON CONFLICT (code) DO UPDATE SET
  case_title = EXCLUDED.case_title,
  case_number = EXCLUDED.case_number,
  case_type = EXCLUDED.case_type,
  court = EXCLUDED.court,
  parties = EXCLUDED.parties,
  status = EXCLUDED.status,
  remarks = EXCLUDED.remarks,
  report_case_number = EXCLUDED.report_case_number,
  filing_date = EXCLUDED.filing_date,
  last_updated = EXCLUDED.last_updated;

-- PHASE 3: INSERT verbatim Status/Remarks
INSERT INTO public.case_status_updates (case_id, sort_order, body)
SELECT c.id, v.sort_order, v.body
FROM public.cases c
CROSS JOIN (VALUES
  (1, 'No status/remarks text is recorded in the supplied Status/Remarks cells for this entry.')
) AS v(sort_order, body)
WHERE c.code = 'c-colobong-001';

-- CASE #15: Mrs. Virginia E. Pagunuran (Metrofab Metal Design)
INSERT INTO public.cases (
  code, case_title, case_number, case_type, court, parties, status,
  remarks, report_case_number, filing_date, last_updated
) VALUES (
  'c-pagunuran-001',
  'Mrs. Virginia E. Pagunuran (Metrofab Metal Design)',
  NULL,
  'Pre-litigation',
  NULL,
  'Republic of the Philippines, rep. by DOST-RO2 vs. Virginia E. Pagunuran',
  'Pending'::public.case_status,
  'No status/remarks text is recorded in the supplied Status/Remarks cells for this entry.',
  15,
  '2023-01-01',
  '2023-01-01'
) ON CONFLICT (code) DO UPDATE SET
  case_title = EXCLUDED.case_title,
  case_number = EXCLUDED.case_number,
  case_type = EXCLUDED.case_type,
  court = EXCLUDED.court,
  parties = EXCLUDED.parties,
  status = EXCLUDED.status,
  remarks = EXCLUDED.remarks,
  report_case_number = EXCLUDED.report_case_number,
  filing_date = EXCLUDED.filing_date,
  last_updated = EXCLUDED.last_updated;

-- PHASE 3: INSERT verbatim Status/Remarks
INSERT INTO public.case_status_updates (case_id, sort_order, body)
SELECT c.id, v.sort_order, v.body
FROM public.cases c
CROSS JOIN (VALUES
  (1, 'No status/remarks text is recorded in the supplied Status/Remarks cells for this entry.')
) AS v(sort_order, body)
WHERE c.code = 'c-pagunuran-001';

-- CASE #16: Mrs. Sonia B. Massalang & Mr. Nicasio L. Baloran (HPT Store Food Produ
INSERT INTO public.cases (
  code, case_title, case_number, case_type, court, parties, status,
  remarks, report_case_number, filing_date, last_updated
) VALUES (
  'c-massalang-001',
  'Mrs. Sonia B. Massalang & Mr. Nicasio L. Baloran (HPT Store Food Product)',
  NULL,
  'Pre-litigation',
  NULL,
  'Republic of the Philippines, rep. by DOST-RO2 vs. Sonia B. Massalang & Nicasio L. Baloran',
  'Pending'::public.case_status,
  'No status/remarks text is recorded in the supplied Status/Remarks cells for this entry.',
  16,
  '2023-01-01',
  '2023-01-01'
) ON CONFLICT (code) DO UPDATE SET
  case_title = EXCLUDED.case_title,
  case_number = EXCLUDED.case_number,
  case_type = EXCLUDED.case_type,
  court = EXCLUDED.court,
  parties = EXCLUDED.parties,
  status = EXCLUDED.status,
  remarks = EXCLUDED.remarks,
  report_case_number = EXCLUDED.report_case_number,
  filing_date = EXCLUDED.filing_date,
  last_updated = EXCLUDED.last_updated;

-- PHASE 3: INSERT verbatim Status/Remarks
INSERT INTO public.case_status_updates (case_id, sort_order, body)
SELECT c.id, v.sort_order, v.body
FROM public.cases c
CROSS JOIN (VALUES
  (1, 'No status/remarks text is recorded in the supplied Status/Remarks cells for this entry.')
) AS v(sort_order, body)
WHERE c.code = 'c-massalang-001';

-- CASE #17: Mrs. Maricel N. Cruz (MMC Grain Training)
INSERT INTO public.cases (
  code, case_title, case_number, case_type, court, parties, status,
  remarks, report_case_number, filing_date, last_updated
) VALUES (
  'c-cruz-001',
  'Mrs. Maricel N. Cruz (MMC Grain Training)',
  NULL,
  'Pre-litigation',
  NULL,
  'Republic of the Philippines, rep. by DOST-RO2 vs. Maricel N. Cruz',
  'Pending'::public.case_status,
  'No status/remarks text is recorded in the supplied Status/Remarks cells for this entry.',
  17,
  '2023-01-01',
  '2023-01-01'
) ON CONFLICT (code) DO UPDATE SET
  case_title = EXCLUDED.case_title,
  case_number = EXCLUDED.case_number,
  case_type = EXCLUDED.case_type,
  court = EXCLUDED.court,
  parties = EXCLUDED.parties,
  status = EXCLUDED.status,
  remarks = EXCLUDED.remarks,
  report_case_number = EXCLUDED.report_case_number,
  filing_date = EXCLUDED.filing_date,
  last_updated = EXCLUDED.last_updated;

-- PHASE 3: INSERT verbatim Status/Remarks
INSERT INTO public.case_status_updates (case_id, sort_order, body)
SELECT c.id, v.sort_order, v.body
FROM public.cases c
CROSS JOIN (VALUES
  (1, 'No status/remarks text is recorded in the supplied Status/Remarks cells for this entry.')
) AS v(sort_order, body)
WHERE c.code = 'c-cruz-001';

-- CASE #18: Mrs. Wilianda P. Tumbali (Wilmar's Food Product)
INSERT INTO public.cases (
  code, case_title, case_number, case_type, court, parties, status,
  remarks, report_case_number, filing_date, last_updated
) VALUES (
  'c-tumbali-001',
  'Mrs. Wilianda P. Tumbali (Wilmar''s Food Product)',
  NULL,
  'Pre-litigation',
  NULL,
  'Republic of the Philippines, rep. by DOST-RO2 vs. Wilianda P. Tumbali',
  'Pending'::public.case_status,
  'No status/remarks text is recorded in the supplied Status/Remarks cells for this entry.',
  18,
  '2023-01-01',
  '2023-01-01'
) ON CONFLICT (code) DO UPDATE SET
  case_title = EXCLUDED.case_title,
  case_number = EXCLUDED.case_number,
  case_type = EXCLUDED.case_type,
  court = EXCLUDED.court,
  parties = EXCLUDED.parties,
  status = EXCLUDED.status,
  remarks = EXCLUDED.remarks,
  report_case_number = EXCLUDED.report_case_number,
  filing_date = EXCLUDED.filing_date,
  last_updated = EXCLUDED.last_updated;

-- PHASE 3: INSERT verbatim Status/Remarks
INSERT INTO public.case_status_updates (case_id, sort_order, body)
SELECT c.id, v.sort_order, v.body
FROM public.cases c
CROSS JOIN (VALUES
  (1, 'No status/remarks text is recorded in the supplied Status/Remarks cells for this entry.')
) AS v(sort_order, body)
WHERE c.code = 'c-tumbali-001';

-- CASE #19: Margarita S. Abalos, MS Abalos Furniture Shop
INSERT INTO public.cases (
  code, case_title, case_number, case_type, court, parties, status,
  remarks, report_case_number, filing_date, last_updated
) VALUES (
  'c-abalos-001',
  'Margarita S. Abalos, MS Abalos Furniture Shop',
  NULL,
  'Pre-litigation',
  NULL,
  'Republic of the Philippines, rep. by DOST-RO2 vs. Margarita S. Abalos, MS Abalos Furniture Shop',
  'Pending'::public.case_status,
  'Per narrative report attached to submitted documents, SETUP proponents cannot be located anymore. Hence, under letter dated November 8, 2022, the DOST-RO2 was advised that it is prudent that the complaints for said cases be not drafted at present, since they will most likely not proceed or may just be archived by the court for failure to serve summons.',
  19,
  '2022-11-08',
  '2022-11-08'
) ON CONFLICT (code) DO UPDATE SET
  case_title = EXCLUDED.case_title,
  case_number = EXCLUDED.case_number,
  case_type = EXCLUDED.case_type,
  court = EXCLUDED.court,
  parties = EXCLUDED.parties,
  status = EXCLUDED.status,
  remarks = EXCLUDED.remarks,
  report_case_number = EXCLUDED.report_case_number,
  filing_date = EXCLUDED.filing_date,
  last_updated = EXCLUDED.last_updated;

-- PHASE 3: INSERT verbatim Status/Remarks
INSERT INTO public.case_status_updates (case_id, sort_order, body)
SELECT c.id, v.sort_order, v.body
FROM public.cases c
CROSS JOIN (VALUES
  (1, 'Per narrative report attached to submitted documents, SETUP proponents cannot be located anymore. Hence, under letter dated November 8, 2022, the DOST-RO2 was advised that it is prudent that the complaints for said cases be not drafted at present, since they will most likely not proceed or may just be archived by the court for failure to serve summons.')
) AS v(sort_order, body)
WHERE c.code = 'c-abalos-001';

-- CASE #20: Atty. Aleth Joyce T. Cubacub, 24/7 Ice Corner
INSERT INTO public.cases (
  code, case_title, case_number, case_type, court, parties, status,
  remarks, report_case_number, filing_date, last_updated
) VALUES (
  'c-cubacub-001',
  'Atty. Aleth Joyce T. Cubacub, 24/7 Ice Corner',
  NULL,
  'Pre-litigation',
  NULL,
  'Republic of the Philippines, rep. by DOST-RO2 vs. Atty. Aleth Joyce T. Cubacub, 24/7 Ice Corner',
  'Pending'::public.case_status,
  'Awaiting information and further instructions from DOST-RO2.',
  20,
  '2023-01-01',
  '2023-01-01'
) ON CONFLICT (code) DO UPDATE SET
  case_title = EXCLUDED.case_title,
  case_number = EXCLUDED.case_number,
  case_type = EXCLUDED.case_type,
  court = EXCLUDED.court,
  parties = EXCLUDED.parties,
  status = EXCLUDED.status,
  remarks = EXCLUDED.remarks,
  report_case_number = EXCLUDED.report_case_number,
  filing_date = EXCLUDED.filing_date,
  last_updated = EXCLUDED.last_updated;

-- PHASE 3: INSERT verbatim Status/Remarks
INSERT INTO public.case_status_updates (case_id, sort_order, body)
SELECT c.id, v.sort_order, v.body
FROM public.cases c
CROSS JOIN (VALUES
  (1, 'Awaiting information and further instructions from DOST-RO2.')
) AS v(sort_order, body)
WHERE c.code = 'c-cubacub-001';

-- CASE #21: Filomena L. Villanueva (A.C. Villanueva Merchandise)
INSERT INTO public.cases (
  code, case_title, case_number, case_type, court, parties, status,
  remarks, report_case_number, filing_date, last_updated
) VALUES (
  'c-villanueva-001',
  'Filomena L. Villanueva (A.C. Villanueva Merchandise)',
  NULL,
  'Small Claims',
  NULL,
  'Republic of the Philippines, rep. by DOST-RO2 vs. Filomena L. Villanueva',
  'Pending'::public.case_status,
  'Informed the DOST-RO2 under letter dated November 8, 2022 that these are Small Claims Cases, where the appearance of attorneys are not allowed. However, OSG will assist in the preparation of the Statement of Claim (SCC Form) and the affidavits of the witness/es.',
  21,
  '2022-11-08',
  '2022-11-08'
) ON CONFLICT (code) DO UPDATE SET
  case_title = EXCLUDED.case_title,
  case_number = EXCLUDED.case_number,
  case_type = EXCLUDED.case_type,
  court = EXCLUDED.court,
  parties = EXCLUDED.parties,
  status = EXCLUDED.status,
  remarks = EXCLUDED.remarks,
  report_case_number = EXCLUDED.report_case_number,
  filing_date = EXCLUDED.filing_date,
  last_updated = EXCLUDED.last_updated;

-- PHASE 3: INSERT verbatim Status/Remarks
INSERT INTO public.case_status_updates (case_id, sort_order, body)
SELECT c.id, v.sort_order, v.body
FROM public.cases c
CROSS JOIN (VALUES
  (1, 'Informed the DOST-RO2 under letter dated November 8, 2022 that these are Small Claims Cases, where the appearance of attorneys are not allowed. However, OSG will assist in the preparation of the Statement of Claim (SCC Form) and the affidavits of the witness/es.')
) AS v(sort_order, body)
WHERE c.code = 'c-villanueva-001';

-- CASE #22: Constantina S. Galapon (CSG Palay and Corn Buying Station)
INSERT INTO public.cases (
  code, case_title, case_number, case_type, court, parties, status,
  remarks, report_case_number, filing_date, last_updated
) VALUES (
  'c-galapon-001',
  'Constantina S. Galapon (CSG Palay and Corn Buying Station)',
  NULL,
  'Small Claims',
  NULL,
  'Republic of the Philippines, rep. by DOST-RO2 vs. Constantina S. Galapon',
  'Pending'::public.case_status,
  'Not allowed. However, the OSG will assist in the preparation of the Statement of Claim (SCC Form) and the Affidavit of the witnesses.',
  22,
  '2023-03-15',
  '2023-03-15'
) ON CONFLICT (code) DO UPDATE SET
  case_title = EXCLUDED.case_title,
  case_number = EXCLUDED.case_number,
  case_type = EXCLUDED.case_type,
  court = EXCLUDED.court,
  parties = EXCLUDED.parties,
  status = EXCLUDED.status,
  remarks = EXCLUDED.remarks,
  report_case_number = EXCLUDED.report_case_number,
  filing_date = EXCLUDED.filing_date,
  last_updated = EXCLUDED.last_updated;

-- PHASE 3: INSERT verbatim Status/Remarks
INSERT INTO public.case_status_updates (case_id, sort_order, body)
SELECT c.id, v.sort_order, v.body
FROM public.cases c
CROSS JOIN (VALUES
  (1, 'Not allowed. However, the OSG will assist in the preparation of the Statement of Claim (SCC Form) and the Affidavit of the witnesses.'),
  (2, 'Conducted meeting last March 15, 2023 with PSTO personnel regarding the drafting of the SCC Form, affidavits and filing of small claims cases.')
) AS v(sort_order, body)
WHERE c.code = 'c-galapon-001';

-- CASE #23: Erlinda Tomas (Luyang's Women Association)
INSERT INTO public.cases (
  code, case_title, case_number, case_type, court, parties, status,
  remarks, report_case_number, filing_date, last_updated
) VALUES (
  'c-tomas-001',
  'Erlinda Tomas (Luyang''s Women Association)',
  NULL,
  'Pre-litigation',
  NULL,
  'Republic of the Philippines, rep. by DOST-RO2 vs. Erlinda Tomas',
  'Pending'::public.case_status,
  'Awaiting drafts of SCC Form and affidavits from PSTOs for review and editing.',
  23,
  '2023-01-01',
  '2023-01-01'
) ON CONFLICT (code) DO UPDATE SET
  case_title = EXCLUDED.case_title,
  case_number = EXCLUDED.case_number,
  case_type = EXCLUDED.case_type,
  court = EXCLUDED.court,
  parties = EXCLUDED.parties,
  status = EXCLUDED.status,
  remarks = EXCLUDED.remarks,
  report_case_number = EXCLUDED.report_case_number,
  filing_date = EXCLUDED.filing_date,
  last_updated = EXCLUDED.last_updated;

-- PHASE 3: INSERT verbatim Status/Remarks
INSERT INTO public.case_status_updates (case_id, sort_order, body)
SELECT c.id, v.sort_order, v.body
FROM public.cases c
CROSS JOIN (VALUES
  (1, 'Awaiting drafts of SCC Form and affidavits from PSTOs for review and editing.')
) AS v(sort_order, body)
WHERE c.code = 'c-tomas-001';

-- CASE #24: Jun-R P. Domingo (JM Furniture Shop) [Small Claims Case]
INSERT INTO public.cases (
  code, case_title, case_number, case_type, court, parties, status,
  remarks, report_case_number, filing_date, last_updated
) VALUES (
  'c-domingo-001',
  'Jun-R P. Domingo (JM Furniture Shop) [Small Claims Case]',
  NULL,
  'Small Claims',
  NULL,
  'Republic of the Philippines, rep. by DOST-RO2 vs. Jun-R P. Domingo',
  'Pending'::public.case_status,
  'Conducted meeting last July 31, 2023 via MS Teams.',
  24,
  '2023-07-31',
  '2023-08-07'
) ON CONFLICT (code) DO UPDATE SET
  case_title = EXCLUDED.case_title,
  case_number = EXCLUDED.case_number,
  case_type = EXCLUDED.case_type,
  court = EXCLUDED.court,
  parties = EXCLUDED.parties,
  status = EXCLUDED.status,
  remarks = EXCLUDED.remarks,
  report_case_number = EXCLUDED.report_case_number,
  filing_date = EXCLUDED.filing_date,
  last_updated = EXCLUDED.last_updated;

-- PHASE 3: INSERT verbatim Status/Remarks
INSERT INTO public.case_status_updates (case_id, sort_order, body)
SELECT c.id, v.sort_order, v.body
FROM public.cases c
CROSS JOIN (VALUES
  (1, 'Conducted meeting last July 31, 2023 via MS Teams.'),
  (2, 'Reviewed and edited SCC Form and Affidavit and sent them back via email, with instructions on August 7, 2023 to Ms. Daisy Simon.'),
  (3, 'Awaiting update from PSTO.')
) AS v(sort_order, body)
WHERE c.code = 'c-domingo-001';

-- CASE #25: Fiordeliza V. Uy / Ron Mikhail V. Uy (Aljuron Foods)
INSERT INTO public.cases (
  code, case_title, case_number, case_type, court, parties, status,
  remarks, report_case_number, filing_date, last_updated
) VALUES (
  'c-uy-001',
  'Fiordeliza V. Uy / Ron Mikhail V. Uy (Aljuron Foods)',
  NULL,
  'Pre-litigation',
  NULL,
  'Republic of the Philippines, rep. by DOST-RO2 vs. Fiordeliza V. Uy / Ron Mikhail V. Uy',
  'Pending'::public.case_status,
  'Sent preliminary questions to PSTO personnel for purposes of determining the witnesses. However, after receiving their answers, none of them appear to be competent witnesses for the case.',
  25,
  '2023-01-01',
  '2023-01-01'
) ON CONFLICT (code) DO UPDATE SET
  case_title = EXCLUDED.case_title,
  case_number = EXCLUDED.case_number,
  case_type = EXCLUDED.case_type,
  court = EXCLUDED.court,
  parties = EXCLUDED.parties,
  status = EXCLUDED.status,
  remarks = EXCLUDED.remarks,
  report_case_number = EXCLUDED.report_case_number,
  filing_date = EXCLUDED.filing_date,
  last_updated = EXCLUDED.last_updated;

-- PHASE 3: INSERT verbatim Status/Remarks
INSERT INTO public.case_status_updates (case_id, sort_order, body)
SELECT c.id, v.sort_order, v.body
FROM public.cases c
CROSS JOIN (VALUES
  (1, 'Sent preliminary questions to PSTO personnel for purposes of determining the witnesses. However, after receiving their answers, none of them appear to be competent witnesses for the case.')
) AS v(sort_order, body)
WHERE c.code = 'c-uy-001';

-- CASE #26: Roberto C. Duerme (Roel's Furniture)
INSERT INTO public.cases (
  code, case_title, case_number, case_type, court, parties, status,
  remarks, report_case_number, filing_date, last_updated
) VALUES (
  'c-duerme-001',
  'Roberto C. Duerme (Roel''s Furniture)',
  NULL,
  'Pre-litigation',
  NULL,
  'Republic of the Philippines, rep. by DOST-RO2 vs. Roberto C. Duerme',
  'Pending'::public.case_status,
  'Upon meeting with PD Nora, the facts of the case need further clarification.',
  26,
  '2023-01-01',
  '2023-01-01'
) ON CONFLICT (code) DO UPDATE SET
  case_title = EXCLUDED.case_title,
  case_number = EXCLUDED.case_number,
  case_type = EXCLUDED.case_type,
  court = EXCLUDED.court,
  parties = EXCLUDED.parties,
  status = EXCLUDED.status,
  remarks = EXCLUDED.remarks,
  report_case_number = EXCLUDED.report_case_number,
  filing_date = EXCLUDED.filing_date,
  last_updated = EXCLUDED.last_updated;

-- PHASE 3: INSERT verbatim Status/Remarks
INSERT INTO public.case_status_updates (case_id, sort_order, body)
SELECT c.id, v.sort_order, v.body
FROM public.cases c
CROSS JOIN (VALUES
  (1, 'Upon meeting with PD Nora, the facts of the case need further clarification.'),
  (2, 'Already interviewed Ms. Clarenet Balderas and Mr. Patrick Cristobal.'),
  (3, 'Awaiting documents from Mr. Patrick Cristobal.'),
  (4, 'Upon receipt of the documents, for Judicial Affidavit taking of:'),
  (5, '  PD Lucio Calimag (already with answers but his JA may be dispensed with)'),
  (6, '  Ms. Clarenet Balderas'),
  (7, '  Mr. Patrick Cristobal'),
  (8, 'Personally made a follow-up with Mr. Patrick Cristobal on the document he was previously requested to submit.')
) AS v(sort_order, body)
WHERE c.code = 'c-duerme-001';

-- CASE #27: Alex U. Khong Hun (Herbank Industries)
INSERT INTO public.cases (
  code, case_title, case_number, case_type, court, parties, status,
  remarks, report_case_number, filing_date, last_updated
) VALUES (
  'c-khong-001',
  'Alex U. Khong Hun (Herbank Industries)',
  NULL,
  'Pre-litigation',
  NULL,
  'Republic of the Philippines, rep. by DOST-RO2 vs. Alex U. Khong Hun',
  'Pending'::public.case_status,
  'Sent Demand Letter on February 22, 2023 to DOST-RO2 via LBC for the signature of Regional Director Virginia G. Bilgera.',
  27,
  '2023-02-22',
  '2023-02-22'
) ON CONFLICT (code) DO UPDATE SET
  case_title = EXCLUDED.case_title,
  case_number = EXCLUDED.case_number,
  case_type = EXCLUDED.case_type,
  court = EXCLUDED.court,
  parties = EXCLUDED.parties,
  status = EXCLUDED.status,
  remarks = EXCLUDED.remarks,
  report_case_number = EXCLUDED.report_case_number,
  filing_date = EXCLUDED.filing_date,
  last_updated = EXCLUDED.last_updated;

-- PHASE 3: INSERT verbatim Status/Remarks
INSERT INTO public.case_status_updates (case_id, sort_order, body)
SELECT c.id, v.sort_order, v.body
FROM public.cases c
CROSS JOIN (VALUES
  (1, 'Sent Demand Letter on February 22, 2023 to DOST-RO2 via LBC for the signature of Regional Director Virginia G. Bilgera.'),
  (2, 'Awaiting further instructions from DOST-RO2.')
) AS v(sort_order, body)
WHERE c.code = 'c-khong-001';

-- CASE #28: Rosalia Garcia (Upgrading the equipment and Facilities for Feedmill an
INSERT INTO public.cases (
  code, case_title, case_number, case_type, court, parties, status,
  remarks, report_case_number, filing_date, last_updated
) VALUES (
  'c-garcia-001',
  'Rosalia Garcia (Upgrading the equipment and Facilities for Feedmill and Meat Processing of New Tumauini)',
  NULL,
  'Pre-litigation',
  NULL,
  'Republic of the Philippines, rep. by DOST-RO2 vs. Rosalia Garcia',
  'Pending'::public.case_status,
  'Sent preliminary questions to PSTO personnel for purposes of determining the witnesses. However, after receiving their answers, none of them appear to be competent witnesses for the case.',
  28,
  '2023-01-01',
  '2023-01-01'
) ON CONFLICT (code) DO UPDATE SET
  case_title = EXCLUDED.case_title,
  case_number = EXCLUDED.case_number,
  case_type = EXCLUDED.case_type,
  court = EXCLUDED.court,
  parties = EXCLUDED.parties,
  status = EXCLUDED.status,
  remarks = EXCLUDED.remarks,
  report_case_number = EXCLUDED.report_case_number,
  filing_date = EXCLUDED.filing_date,
  last_updated = EXCLUDED.last_updated;

-- PHASE 3: INSERT verbatim Status/Remarks
INSERT INTO public.case_status_updates (case_id, sort_order, body)
SELECT c.id, v.sort_order, v.body
FROM public.cases c
CROSS JOIN (VALUES
  (1, 'Sent preliminary questions to PSTO personnel for purposes of determining the witnesses. However, after receiving their answers, none of them appear to be competent witnesses for the case.')
) AS v(sort_order, body)
WHERE c.code = 'c-garcia-001';

-- CASE #29: Artemio Dimaculangan (Pan de Alicia)
INSERT INTO public.cases (
  code, case_title, case_number, case_type, court, parties, status,
  remarks, report_case_number, filing_date, last_updated
) VALUES (
  'c-dimaculangan-001',
  'Artemio Dimaculangan (Pan de Alicia)',
  NULL,
  'Pre-litigation',
  NULL,
  'Republic of the Philippines, rep. by DOST-RO2 vs. Artemio Dimaculangan',
  'Pending'::public.case_status,
  'Awaiting further instructions from DOST-RO2.',
  29,
  '2023-01-01',
  '2023-01-01'
) ON CONFLICT (code) DO UPDATE SET
  case_title = EXCLUDED.case_title,
  case_number = EXCLUDED.case_number,
  case_type = EXCLUDED.case_type,
  court = EXCLUDED.court,
  parties = EXCLUDED.parties,
  status = EXCLUDED.status,
  remarks = EXCLUDED.remarks,
  report_case_number = EXCLUDED.report_case_number,
  filing_date = EXCLUDED.filing_date,
  last_updated = EXCLUDED.last_updated;

-- PHASE 3: INSERT verbatim Status/Remarks
INSERT INTO public.case_status_updates (case_id, sort_order, body)
SELECT c.id, v.sort_order, v.body
FROM public.cases c
CROSS JOIN (VALUES
  (1, 'Awaiting further instructions from DOST-RO2.')
) AS v(sort_order, body)
WHERE c.code = 'c-dimaculangan-001';

-- CASE #30: Amor C. Mallare (KASAKA Rice Mill)
INSERT INTO public.cases (
  code, case_title, case_number, case_type, court, parties, status,
  remarks, report_case_number, filing_date, last_updated
) VALUES (
  'c-mallare-001',
  'Amor C. Mallare (KASAKA Rice Mill)',
  NULL,
  'Pre-litigation',
  NULL,
  'Republic of the Philippines, rep. by DOST-RO2 vs. Amor C. Mallare',
  'Pending'::public.case_status,
  'Sent Demand Letter dated March 30, 2023 on March 31, 2023 to DOST-RO2 via LBC for the signature of Regional Director Virginia G. Bilgera.',
  30,
  '2023-03-30',
  '2023-03-31'
) ON CONFLICT (code) DO UPDATE SET
  case_title = EXCLUDED.case_title,
  case_number = EXCLUDED.case_number,
  case_type = EXCLUDED.case_type,
  court = EXCLUDED.court,
  parties = EXCLUDED.parties,
  status = EXCLUDED.status,
  remarks = EXCLUDED.remarks,
  report_case_number = EXCLUDED.report_case_number,
  filing_date = EXCLUDED.filing_date,
  last_updated = EXCLUDED.last_updated;

-- PHASE 3: INSERT verbatim Status/Remarks
INSERT INTO public.case_status_updates (case_id, sort_order, body)
SELECT c.id, v.sort_order, v.body
FROM public.cases c
CROSS JOIN (VALUES
  (1, 'Sent Demand Letter dated March 30, 2023 on March 31, 2023 to DOST-RO2 via LBC for the signature of Regional Director Virginia G. Bilgera.'),
  (2, 'Awaiting further instructions from DOST-RO2.')
) AS v(sort_order, body)
WHERE c.code = 'c-mallare-001';

-- CASE #31: Leviticus A. Lamiere (RDL Piggery Farm)
INSERT INTO public.cases (
  code, case_title, case_number, case_type, court, parties, status,
  remarks, report_case_number, filing_date, last_updated
) VALUES (
  'c-lamiere-001',
  'Leviticus A. Lamiere (RDL Piggery Farm)',
  NULL,
  'Pre-litigation',
  NULL,
  'Republic of the Philippines, rep. by DOST-RO2 vs. Leviticus A. Lamiere',
  'Pending'::public.case_status,
  'Received November 10, 2023 Endorsement Letter with attached documents from Regional Director Virginia G. Bilgera.',
  31,
  '2023-11-10',
  '2023-11-10'
) ON CONFLICT (code) DO UPDATE SET
  case_title = EXCLUDED.case_title,
  case_number = EXCLUDED.case_number,
  case_type = EXCLUDED.case_type,
  court = EXCLUDED.court,
  parties = EXCLUDED.parties,
  status = EXCLUDED.status,
  remarks = EXCLUDED.remarks,
  report_case_number = EXCLUDED.report_case_number,
  filing_date = EXCLUDED.filing_date,
  last_updated = EXCLUDED.last_updated;

-- PHASE 3: INSERT verbatim Status/Remarks
INSERT INTO public.case_status_updates (case_id, sort_order, body)
SELECT c.id, v.sort_order, v.body
FROM public.cases c
CROSS JOIN (VALUES
  (1, 'Received November 10, 2023 Endorsement Letter with attached documents from Regional Director Virginia G. Bilgera.'),
  (2, 'For scheduling of meeting by RPMO with concerned PSTO personnel.')
) AS v(sort_order, body)
WHERE c.code = 'c-lamiere-001';

-- CASE #32: Sps. Charlton V. Pua and Maria Cecilia B. Pua (Golden Rain Grain Cente
INSERT INTO public.cases (
  code, case_title, case_number, case_type, court, parties, status,
  remarks, report_case_number, filing_date, last_updated
) VALUES (
  'c-pua-001',
  'Sps. Charlton V. Pua and Maria Cecilia B. Pua (Golden Rain Grain Center)',
  NULL,
  'Pre-litigation',
  NULL,
  'Republic of the Philippines, rep. by DOST-RO2 vs. Sps. Charlton V. Pua and Maria Cecilia B. Pua',
  'Pending'::public.case_status,
  'Received November 10, 2023 Endorsement Letter with attached documents from Regional Director Virginia G. Bilgera.',
  32,
  '2023-11-10',
  '2023-11-10'
) ON CONFLICT (code) DO UPDATE SET
  case_title = EXCLUDED.case_title,
  case_number = EXCLUDED.case_number,
  case_type = EXCLUDED.case_type,
  court = EXCLUDED.court,
  parties = EXCLUDED.parties,
  status = EXCLUDED.status,
  remarks = EXCLUDED.remarks,
  report_case_number = EXCLUDED.report_case_number,
  filing_date = EXCLUDED.filing_date,
  last_updated = EXCLUDED.last_updated;

-- PHASE 3: INSERT verbatim Status/Remarks
INSERT INTO public.case_status_updates (case_id, sort_order, body)
SELECT c.id, v.sort_order, v.body
FROM public.cases c
CROSS JOIN (VALUES
  (1, 'Received November 10, 2023 Endorsement Letter with attached documents from Regional Director Virginia G. Bilgera.'),
  (2, 'For scheduling of meeting by RPMO with concerned PSTO personnel.')
) AS v(sort_order, body)
WHERE c.code = 'c-pua-001';

-- CASE #33: Ellison A. Delos Santos (DS Poultry Farm)
INSERT INTO public.cases (
  code, case_title, case_number, case_type, court, parties, status,
  remarks, report_case_number, filing_date, last_updated
) VALUES (
  'c-delossantos-001',
  'Ellison A. Delos Santos (DS Poultry Farm)',
  NULL,
  'Pre-litigation',
  NULL,
  'Republic of the Philippines, rep. by DOST-RO2 vs. Ellison A. Delos Santos',
  'Pending'::public.case_status,
  'Received November 10, 2023 Endorsement Letter with attached documents from Regional Director Virginia G. Bilgera.',
  33,
  '2023-11-10',
  '2023-11-10'
) ON CONFLICT (code) DO UPDATE SET
  case_title = EXCLUDED.case_title,
  case_number = EXCLUDED.case_number,
  case_type = EXCLUDED.case_type,
  court = EXCLUDED.court,
  parties = EXCLUDED.parties,
  status = EXCLUDED.status,
  remarks = EXCLUDED.remarks,
  report_case_number = EXCLUDED.report_case_number,
  filing_date = EXCLUDED.filing_date,
  last_updated = EXCLUDED.last_updated;

-- PHASE 3: INSERT verbatim Status/Remarks
INSERT INTO public.case_status_updates (case_id, sort_order, body)
SELECT c.id, v.sort_order, v.body
FROM public.cases c
CROSS JOIN (VALUES
  (1, 'Received November 10, 2023 Endorsement Letter with attached documents from Regional Director Virginia G. Bilgera.'),
  (2, 'For scheduling of meeting by RPMO with concerned PSTO personnel.')
) AS v(sort_order, body)
WHERE c.code = 'c-delossantos-001';

-- CASE #34: Mr. Elpidio V. Barien & Mrs. Emma Ruth B. Barien (H-I-Q BB Bakeshop)
INSERT INTO public.cases (
  code, case_title, case_number, case_type, court, parties, status,
  remarks, report_case_number, filing_date, last_updated
) VALUES (
  'c-barien-001',
  'Mr. Elpidio V. Barien & Mrs. Emma Ruth B. Barien (H-I-Q BB Bakeshop)',
  NULL,
  'Pre-litigation',
  NULL,
  'Republic of the Philippines, rep. by DOST-RO2 vs. Elpidio V. Barien & Emma Ruth B. Barien',
  'Pending'::public.case_status,
  'Received November 10, 2023 Endorsement Letter with attached documents from Regional Director Virginia G. Bilgera.',
  34,
  '2023-11-10',
  '2023-11-10'
) ON CONFLICT (code) DO UPDATE SET
  case_title = EXCLUDED.case_title,
  case_number = EXCLUDED.case_number,
  case_type = EXCLUDED.case_type,
  court = EXCLUDED.court,
  parties = EXCLUDED.parties,
  status = EXCLUDED.status,
  remarks = EXCLUDED.remarks,
  report_case_number = EXCLUDED.report_case_number,
  filing_date = EXCLUDED.filing_date,
  last_updated = EXCLUDED.last_updated;

-- PHASE 3: INSERT verbatim Status/Remarks
INSERT INTO public.case_status_updates (case_id, sort_order, body)
SELECT c.id, v.sort_order, v.body
FROM public.cases c
CROSS JOIN (VALUES
  (1, 'Received November 10, 2023 Endorsement Letter with attached documents from Regional Director Virginia G. Bilgera.'),
  (2, 'For scheduling of meeting by RPMO with concerned PSTO personnel.')
) AS v(sort_order, body)
WHERE c.code = 'c-barien-001';

-- CASE #35: Ricardo B. Navis, Jr. (Makabagong Gabay sa Kalusugan)
INSERT INTO public.cases (
  code, case_title, case_number, case_type, court, parties, status,
  remarks, report_case_number, filing_date, last_updated
) VALUES (
  'c-navis-001',
  'Ricardo B. Navis, Jr. (Makabagong Gabay sa Kalusugan)',
  NULL,
  'Small Claims',
  NULL,
  'Republic of the Philippines, rep. by DOST-RO2 vs. Ricardo B. Navis, Jr.',
  'Pending'::public.case_status,
  'Upon update of PD Nuestro, the OSG was informed that the Small Claims Case was not filed.',
  35,
  '2023-01-01',
  '2023-01-01'
) ON CONFLICT (code) DO UPDATE SET
  case_title = EXCLUDED.case_title,
  case_number = EXCLUDED.case_number,
  case_type = EXCLUDED.case_type,
  court = EXCLUDED.court,
  parties = EXCLUDED.parties,
  status = EXCLUDED.status,
  remarks = EXCLUDED.remarks,
  report_case_number = EXCLUDED.report_case_number,
  filing_date = EXCLUDED.filing_date,
  last_updated = EXCLUDED.last_updated;

-- PHASE 3: INSERT verbatim Status/Remarks
INSERT INTO public.case_status_updates (case_id, sort_order, body)
SELECT c.id, v.sort_order, v.body
FROM public.cases c
CROSS JOIN (VALUES
  (1, 'Upon update of PD Nuestro, the OSG was informed that the Small Claims Case was not filed.'),
  (2, 'For RPMO''s action.')
) AS v(sort_order, body)
WHERE c.code = 'c-navis-001';

-- CASE #36: Antonio Y. Pinzon (AYP Dressing Plant)
INSERT INTO public.cases (
  code, case_title, case_number, case_type, court, parties, status,
  remarks, report_case_number, filing_date, last_updated
) VALUES (
  'c-pinzon-001',
  'Antonio Y. Pinzon (AYP Dressing Plant)',
  NULL,
  'Pre-litigation',
  NULL,
  'Republic of the Philippines, rep. by DOST-RO2 vs. Antonio Y. Pinzon',
  'Pending'::public.case_status,
  'Conducted virtual meeting last May 15, 2023.',
  36,
  '2023-05-15',
  '2023-05-15'
) ON CONFLICT (code) DO UPDATE SET
  case_title = EXCLUDED.case_title,
  case_number = EXCLUDED.case_number,
  case_type = EXCLUDED.case_type,
  court = EXCLUDED.court,
  parties = EXCLUDED.parties,
  status = EXCLUDED.status,
  remarks = EXCLUDED.remarks,
  report_case_number = EXCLUDED.report_case_number,
  filing_date = EXCLUDED.filing_date,
  last_updated = EXCLUDED.last_updated;

-- PHASE 3: INSERT verbatim Status/Remarks
INSERT INTO public.case_status_updates (case_id, sort_order, body)
SELECT c.id, v.sort_order, v.body
FROM public.cases c
CROSS JOIN (VALUES
  (1, 'Conducted virtual meeting last May 15, 2023.'),
  (2, 'Awaiting documents for Judicial Affidavit and Complaint.')
) AS v(sort_order, body)
WHERE c.code = 'c-pinzon-001';

-- CASE #37: Noel G. Pablo
INSERT INTO public.cases (
  code, case_title, case_number, case_type, court, parties, status,
  remarks, report_case_number, filing_date, last_updated
) VALUES (
  'c-pablo-001',
  'Noel G. Pablo',
  NULL,
  'Pre-litigation',
  NULL,
  'Republic of the Philippines, rep. by DOST-RO2 vs. Noel G. Pablo',
  'Pending'::public.case_status,
  'Drafted the Judicial Affidavit of Mr. Angelo Capurian but awaiting documents for completion.',
  37,
  '2023-01-01',
  '2023-01-01'
) ON CONFLICT (code) DO UPDATE SET
  case_title = EXCLUDED.case_title,
  case_number = EXCLUDED.case_number,
  case_type = EXCLUDED.case_type,
  court = EXCLUDED.court,
  parties = EXCLUDED.parties,
  status = EXCLUDED.status,
  remarks = EXCLUDED.remarks,
  report_case_number = EXCLUDED.report_case_number,
  filing_date = EXCLUDED.filing_date,
  last_updated = EXCLUDED.last_updated;

-- PHASE 3: INSERT verbatim Status/Remarks
INSERT INTO public.case_status_updates (case_id, sort_order, body)
SELECT c.id, v.sort_order, v.body
FROM public.cases c
CROSS JOIN (VALUES
  (1, 'Drafted the Judicial Affidavit of Mr. Angelo Capurian but awaiting documents for completion.'),
  (2, 'Received documents from Ms. Nancy Guimmayen.'),
  (3, 'As soon as documents are received from Mr. Capurian, his JA and that of Ma''am Nancy Guimmayen will be taken.')
) AS v(sort_order, body)
WHERE c.code = 'c-pablo-001';

-- CASE #38: Edgar N. Base, Sr. (Base Wood Products)
INSERT INTO public.cases (
  code, case_title, case_number, case_type, court, parties, status,
  remarks, report_case_number, filing_date, last_updated
) VALUES (
  'c-base-001',
  'Edgar N. Base, Sr. (Base Wood Products)',
  NULL,
  'Pre-litigation',
  NULL,
  'Republic of the Philippines, rep. by DOST-RO2 vs. Edgar N. Base, Sr.',
  'Pending'::public.case_status,
  'Conducted meeting last May 23, 2023. As discussed, the PSTO will consult with the record of the Regional Office to check the accuracy of the computation of final amount of proponent''s SETUP obligation. Thereafter, the PSTO will meet Mr. Base, Jr.',
  38,
  '2023-05-23',
  '2023-05-23'
) ON CONFLICT (code) DO UPDATE SET
  case_title = EXCLUDED.case_title,
  case_number = EXCLUDED.case_number,
  case_type = EXCLUDED.case_type,
  court = EXCLUDED.court,
  parties = EXCLUDED.parties,
  status = EXCLUDED.status,
  remarks = EXCLUDED.remarks,
  report_case_number = EXCLUDED.report_case_number,
  filing_date = EXCLUDED.filing_date,
  last_updated = EXCLUDED.last_updated;

-- PHASE 3: INSERT verbatim Status/Remarks
INSERT INTO public.case_status_updates (case_id, sort_order, body)
SELECT c.id, v.sort_order, v.body
FROM public.cases c
CROSS JOIN (VALUES
  (1, 'Conducted meeting last May 23, 2023. As discussed, the PSTO will consult with the record of the Regional Office to check the accuracy of the computation of final amount of proponent''s SETUP obligation. Thereafter, the PSTO will meet Mr. Base, Jr.'),
  (2, 'Awaiting update from PSTO.')
) AS v(sort_order, body)
WHERE c.code = 'c-base-001';

-- CASE #39: Michelle P. Montilla and Jesus T. Taquiqui married to Grandelee D. Taq
INSERT INTO public.cases (
  code, case_title, case_number, case_type, court, parties, status,
  remarks, report_case_number, filing_date, last_updated
) VALUES (
  'c-montilla-001',
  'Michelle P. Montilla and Jesus T. Taquiqui married to Grandelee D. Taquiqui (Starstudio Digital Network)',
  NULL,
  'Small Claims',
  NULL,
  'Republic of the Philippines, rep. by DOST-RO2 vs. Michelle P. Montilla and Jesus T. Taquiqui married to Grandelee D. Taquiqui',
  'Pending'::public.case_status,
  'Conducted meeting on August 18, 2023 via MS Teams with project-in-charge. PSTO was advised that the SETUP case of Anthony L. Lasam (Kiko''s Farm Products Wholesaling) is for filing under Small Claims Cases procedure.',
  39,
  '2023-08-18',
  '2023-08-18'
) ON CONFLICT (code) DO UPDATE SET
  case_title = EXCLUDED.case_title,
  case_number = EXCLUDED.case_number,
  case_type = EXCLUDED.case_type,
  court = EXCLUDED.court,
  parties = EXCLUDED.parties,
  status = EXCLUDED.status,
  remarks = EXCLUDED.remarks,
  report_case_number = EXCLUDED.report_case_number,
  filing_date = EXCLUDED.filing_date,
  last_updated = EXCLUDED.last_updated;

-- PHASE 3: INSERT verbatim Status/Remarks
INSERT INTO public.case_status_updates (case_id, sort_order, body)
SELECT c.id, v.sort_order, v.body
FROM public.cases c
CROSS JOIN (VALUES
  (1, 'Conducted meeting on August 18, 2023 via MS Teams with project-in-charge. PSTO was advised that the SETUP case of Anthony L. Lasam (Kiko''s Farm Products Wholesaling) is for filing under Small Claims Cases procedure.')
) AS v(sort_order, body)
WHERE c.code = 'c-montilla-001';

-- CASE #40: Michelle P. Montilla and Edgardo C. Paraiso (Broom Broom Auto Parts an
INSERT INTO public.cases (
  code, case_title, case_number, case_type, court, parties, status,
  remarks, report_case_number, filing_date, last_updated
) VALUES (
  'c-paraiso-001',
  'Michelle P. Montilla and Edgardo C. Paraiso (Broom Broom Auto Parts and Car Accessories)',
  NULL,
  'Pre-litigation',
  NULL,
  'Republic of the Philippines, rep. by DOST-RO2 vs. Michelle P. Montilla and Edgardo C. Paraiso',
  'Pending'::public.case_status,
  'Received on October 16, 2023 the requested document from Mr. Capurian.',
  40,
  '2023-10-25',
  '2023-10-25'
) ON CONFLICT (code) DO UPDATE SET
  case_title = EXCLUDED.case_title,
  case_number = EXCLUDED.case_number,
  case_type = EXCLUDED.case_type,
  court = EXCLUDED.court,
  parties = EXCLUDED.parties,
  status = EXCLUDED.status,
  remarks = EXCLUDED.remarks,
  report_case_number = EXCLUDED.report_case_number,
  filing_date = EXCLUDED.filing_date,
  last_updated = EXCLUDED.last_updated;

-- PHASE 3: INSERT verbatim Status/Remarks
INSERT INTO public.case_status_updates (case_id, sort_order, body)
SELECT c.id, v.sort_order, v.body
FROM public.cases c
CROSS JOIN (VALUES
  (1, 'Received on October 16, 2023 the requested document from Mr. Capurian.'),
  (2, 'Latest draft Judicial Affidavit of Mr. Capurian was sent via email on October 25, 2023, with request for virtual meeting for the taking of his Judicial Affidavit.'),
  (3, 'Awaiting response anent Mr. Capurian''s available schedule.')
) AS v(sort_order, body)
WHERE c.code = 'c-paraiso-001';

-- CASE #41: Anthony L. Lasam (Kiko's Farm Products Wholesaling)
INSERT INTO public.cases (
  code, case_title, case_number, case_type, court, parties, status,
  remarks, report_case_number, filing_date, last_updated
) VALUES (
  'c-lasam-kikos-001',
  'Anthony L. Lasam (Kiko''s Farm Products Wholesaling)',
  NULL,
  'Small Claims',
  NULL,
  'Republic of the Philippines, rep. by DOST-RO2 vs. Anthony L. Lasam',
  'Pending'::public.case_status,
  'For scheduling of meeting by RPMO with concerned PSTO personnel.',
  41,
  '2023-08-18',
  '2023-08-18'
) ON CONFLICT (code) DO UPDATE SET
  case_title = EXCLUDED.case_title,
  case_number = EXCLUDED.case_number,
  case_type = EXCLUDED.case_type,
  court = EXCLUDED.court,
  parties = EXCLUDED.parties,
  status = EXCLUDED.status,
  remarks = EXCLUDED.remarks,
  report_case_number = EXCLUDED.report_case_number,
  filing_date = EXCLUDED.filing_date,
  last_updated = EXCLUDED.last_updated;

-- PHASE 3: INSERT verbatim Status/Remarks
INSERT INTO public.case_status_updates (case_id, sort_order, body)
SELECT c.id, v.sort_order, v.body
FROM public.cases c
CROSS JOIN (VALUES
  (1, 'For scheduling of meeting by RPMO with concerned PSTO personnel.')
) AS v(sort_order, body)
WHERE c.code = 'c-lasam-kikos-001';

-- CASE #42: Daisy A. Guzman and Joselito A. Guzman (D.A. Guzman Grains Trading)
INSERT INTO public.cases (
  code, case_title, case_number, case_type, court, parties, status,
  remarks, report_case_number, filing_date, last_updated
) VALUES (
  'c-guzman-001',
  'Daisy A. Guzman and Joselito A. Guzman (D.A. Guzman Grains Trading)',
  NULL,
  'Pre-litigation',
  NULL,
  'Republic of the Philippines, rep. by DOST-RO2 vs. Daisy A. Guzman and Joselito A. Guzman',
  'Pending'::public.case_status,
  'As for the two other SETUP accounts, awaiting documents and information in order to start the drafting the Judicial Affidavits and Complaints.',
  42,
  '2019-01-01',
  '2019-01-01'
) ON CONFLICT (code) DO UPDATE SET
  case_title = EXCLUDED.case_title,
  case_number = EXCLUDED.case_number,
  case_type = EXCLUDED.case_type,
  court = EXCLUDED.court,
  parties = EXCLUDED.parties,
  status = EXCLUDED.status,
  remarks = EXCLUDED.remarks,
  report_case_number = EXCLUDED.report_case_number,
  filing_date = EXCLUDED.filing_date,
  last_updated = EXCLUDED.last_updated;

-- PHASE 3: INSERT verbatim Status/Remarks
INSERT INTO public.case_status_updates (case_id, sort_order, body)
SELECT c.id, v.sort_order, v.body
FROM public.cases c
CROSS JOIN (VALUES
  (1, 'As for the two other SETUP accounts, awaiting documents and information in order to start the drafting the Judicial Affidavits and Complaints.')
) AS v(sort_order, body)
WHERE c.code = 'c-guzman-001';

-- CASE #43: Oscar Andres, JARS Furniture and Sash Factory
INSERT INTO public.cases (
  code, case_title, case_number, case_type, court, parties, status,
  remarks, report_case_number, filing_date, last_updated
) VALUES (
  'c-andres-001',
  'Oscar Andres, JARS Furniture and Sash Factory',
  NULL,
  'Pre-litigation',
  NULL,
  'Republic of the Philippines, rep. by DOST-RO2 vs. Oscar Andres, JARS Furniture and Sash Factory',
  'Pending'::public.case_status,
  'Transmitted in 2019 the duly signed Complaint with annexes but for unknown reason, the OSG learned that the same was not filed in court.',
  43,
  '2024-01-29',
  '2024-01-29'
) ON CONFLICT (code) DO UPDATE SET
  case_title = EXCLUDED.case_title,
  case_number = EXCLUDED.case_number,
  case_type = EXCLUDED.case_type,
  court = EXCLUDED.court,
  parties = EXCLUDED.parties,
  status = EXCLUDED.status,
  remarks = EXCLUDED.remarks,
  report_case_number = EXCLUDED.report_case_number,
  filing_date = EXCLUDED.filing_date,
  last_updated = EXCLUDED.last_updated;

-- PHASE 3: INSERT verbatim Status/Remarks
INSERT INTO public.case_status_updates (case_id, sort_order, body)
SELECT c.id, v.sort_order, v.body
FROM public.cases c
CROSS JOIN (VALUES
  (1, 'Transmitted in 2019 the duly signed Complaint with annexes but for unknown reason, the OSG learned that the same was not filed in court.'),
  (2, 'Sent two email requests on January 15, 2024 to Ms. Daisy Simon. Ms. Simon replied on January 29, 2024, and a reply was sent on the same date, requesting Ms. Simon to coordinate with the Regional Office.'),
  (3, 'Awaiting documents and clarifications from both PSTO and DOST-RO2.')
) AS v(sort_order, body)
WHERE c.code = 'c-andres-001';

-- =============================================================================
-- VERIFICATION
-- =============================================================================
SELECT report_case_number, code, LEFT(case_title, 60) AS case_title, status,
  (SELECT COUNT(*) FROM public.case_status_updates u WHERE u.case_id = c.id) AS remark_count
FROM public.cases c
WHERE report_case_number BETWEEN 1 AND 43
ORDER BY report_case_number;

SELECT COUNT(*) AS total_cases FROM public.cases WHERE report_case_number BETWEEN 1 AND 43;
SELECT COUNT(*) AS total_remarks FROM public.case_status_updates u
JOIN public.cases c ON c.id = u.case_id
WHERE c.report_case_number BETWEEN 1 AND 43;

-- Expected: 43 cases, 230 total remark rows
COMMIT;
